## Introduction to Databases

### Miscellaneous Formats

In [1]:
import os
import sys
import time
import datetime
import numpy as np
import pandas as pd

In [2]:
datapath = "../SampleDBs/"

## Saving a txt file

In [3]:
with open(os.path.join(datapath, 'newfile.txt'), mode='w', encoding='utf-8') as f:
    f.write('Weight\t\t72\n')
    f.write('Height\t\t183\n')
    f.write('Age\t\t44\n')
    f.write('Gender\t\tMasculine\n')
    f.write('\n')

## Retrieving a txt file

In [4]:
with open(os.path.join(datapath, 'newfile.txt'), mode='r', encoding='utf-8') as f:
    fulltext = f.read()
    f.seek(0)
    line = f.readline()
    f.seek(0)
    list_of_lines = f.readlines()

In [5]:
print(fulltext)

Weight		72
Height		183
Age		44
Gender		Masculine




In [6]:
print(line)

Weight		72



In [7]:
print(list_of_lines)

['Weight\t\t72\n', 'Height\t\t183\n', 'Age\t\t44\n', 'Gender\t\tMasculine\n', '\n']


In [8]:
#erasing file
os.remove(os.path.join(datapath, 'newfile.txt'))

## Saving Numpy Structures

In [9]:
data = np.linspace(0,1,201)
print(data)

[0.    0.005 0.01  0.015 0.02  0.025 0.03  0.035 0.04  0.045 0.05  0.055
 0.06  0.065 0.07  0.075 0.08  0.085 0.09  0.095 0.1   0.105 0.11  0.115
 0.12  0.125 0.13  0.135 0.14  0.145 0.15  0.155 0.16  0.165 0.17  0.175
 0.18  0.185 0.19  0.195 0.2   0.205 0.21  0.215 0.22  0.225 0.23  0.235
 0.24  0.245 0.25  0.255 0.26  0.265 0.27  0.275 0.28  0.285 0.29  0.295
 0.3   0.305 0.31  0.315 0.32  0.325 0.33  0.335 0.34  0.345 0.35  0.355
 0.36  0.365 0.37  0.375 0.38  0.385 0.39  0.395 0.4   0.405 0.41  0.415
 0.42  0.425 0.43  0.435 0.44  0.445 0.45  0.455 0.46  0.465 0.47  0.475
 0.48  0.485 0.49  0.495 0.5   0.505 0.51  0.515 0.52  0.525 0.53  0.535
 0.54  0.545 0.55  0.555 0.56  0.565 0.57  0.575 0.58  0.585 0.59  0.595
 0.6   0.605 0.61  0.615 0.62  0.625 0.63  0.635 0.64  0.645 0.65  0.655
 0.66  0.665 0.67  0.675 0.68  0.685 0.69  0.695 0.7   0.705 0.71  0.715
 0.72  0.725 0.73  0.735 0.74  0.745 0.75  0.755 0.76  0.765 0.77  0.775
 0.78  0.785 0.79  0.795 0.8   0.805 0.81  0.815 0.

In [10]:
type(data)

numpy.ndarray

In [11]:
np.savetxt(os.path.join(datapath, 'data.dat'), data)

In [12]:
new_data = np.loadtxt(os.path.join(datapath, 'data.dat'))
print(new_data)

[0.    0.005 0.01  0.015 0.02  0.025 0.03  0.035 0.04  0.045 0.05  0.055
 0.06  0.065 0.07  0.075 0.08  0.085 0.09  0.095 0.1   0.105 0.11  0.115
 0.12  0.125 0.13  0.135 0.14  0.145 0.15  0.155 0.16  0.165 0.17  0.175
 0.18  0.185 0.19  0.195 0.2   0.205 0.21  0.215 0.22  0.225 0.23  0.235
 0.24  0.245 0.25  0.255 0.26  0.265 0.27  0.275 0.28  0.285 0.29  0.295
 0.3   0.305 0.31  0.315 0.32  0.325 0.33  0.335 0.34  0.345 0.35  0.355
 0.36  0.365 0.37  0.375 0.38  0.385 0.39  0.395 0.4   0.405 0.41  0.415
 0.42  0.425 0.43  0.435 0.44  0.445 0.45  0.455 0.46  0.465 0.47  0.475
 0.48  0.485 0.49  0.495 0.5   0.505 0.51  0.515 0.52  0.525 0.53  0.535
 0.54  0.545 0.55  0.555 0.56  0.565 0.57  0.575 0.58  0.585 0.59  0.595
 0.6   0.605 0.61  0.615 0.62  0.625 0.63  0.635 0.64  0.645 0.65  0.655
 0.66  0.665 0.67  0.675 0.68  0.685 0.69  0.695 0.7   0.705 0.71  0.715
 0.72  0.725 0.73  0.735 0.74  0.745 0.75  0.755 0.76  0.765 0.77  0.775
 0.78  0.785 0.79  0.795 0.8   0.805 0.81  0.815 0.

In [13]:
#erasing file
os.remove(os.path.join(datapath, 'data.dat'))

In [14]:
x = np.linspace(0, 1, 20)
y = np.random.random(20)
header = "X-Column, Y-Column\n"
header += "This is a second line"

with open(os.path.join(datapath,'data2.dat'), 'wb') as f:
#with open(os.path.join(datapath,'data2.dat'), 'w') as f:   #using text formatting and no binary files
    np.savetxt(f, [], header=header)
    for i in range(20):
        data = np.column_stack((x[i], y[i]))
        np.savetxt(f, data), print(data)
        #f.write('{:4.1f} {:.4f}\n'.format(x[i], y[i]))    #using text formatting and no binary files
        f.flush()

[[0.         0.35995744]]
[[0.05263158 0.02429669]]
[[0.10526316 0.91456658]]
[[0.15789474 0.1015429 ]]
[[0.21052632 0.53368453]]
[[0.26315789 0.93746956]]
[[0.31578947 0.51193851]]
[[0.36842105 0.80576975]]
[[0.42105263 0.21915724]]
[[0.47368421 0.04779344]]
[[0.52631579 0.83928441]]
[[0.57894737 0.17652798]]
[[0.63157895 0.51045553]]
[[0.68421053 0.93770703]]
[[0.73684211 0.33255968]]
[[0.78947368 0.26303772]]
[[0.84210526 0.24584096]]
[[0.89473684 0.01316609]]
[[0.94736842 0.88902065]]
[[1.         0.30492523]]


In [15]:
! cat ../SampleDBs/data2.dat

# X-Column, Y-Column
# This is a second line
0.000000000000000000e+00 3.599574376349565785e-01
5.263157894736841813e-02 2.429668802814788364e-02
1.052631578947368363e-01 9.145665849112072365e-01
1.578947368421052544e-01 1.015428979218716554e-01
2.105263157894736725e-01 5.336845286082815276e-01
2.631578947368420907e-01 9.374695629905477334e-01
3.157894736842105088e-01 5.119385117671290120e-01
3.684210526315789269e-01 8.057697472896294677e-01
4.210526315789473450e-01 2.191572353698321152e-01
4.736842105263157632e-01 4.779344454176259749e-02
5.263157894736841813e-01 8.392844109970266642e-01
5.789473684210526550e-01 1.765279789042919489e-01
6.315789473684210176e-01 5.104555258024013886e-01
6.842105263157893802e-01 9.377070336795269023e-01
7.368421052631578538e-01 3.325596754255929488e-01
7.894736842105263275e-01 2.630377219757922269e-01
8.421052631578946901e-01 2.458409615074957921e-01
8.947368421052630527e-01 1.316609068643392888e-02
9.473684210526315264e-01 8.890206506795464980e-01
1.000

In [16]:
#erasing file
os.remove(os.path.join(datapath, 'data2.dat'))

## Using Pickle

In [17]:
import pickle

data = [1, 1.2, 'a', 'b']

with open(os.path.join(datapath, 'data.pkl'), 'wb') as f:
    pickle.dump(data, f)

In [18]:
with open(os.path.join(datapath, 'data.pkl'), 'rb') as f:
    new_data = pickle.load(f)

print(new_data)

[1, 1.2, 'a', 'b']


Pickle with gzip

In [19]:
import gzip

In [20]:
data2 = [1, 1.2, 'a', 'b']

In [21]:
with gzip.open(os.path.join(datapath, 'data.pkl.gz'), 'wb') as f:
    pickle.dump(data2, f)

In [22]:
with gzip.open(os.path.join(datapath, 'data.pkl.gz'), 'rb') as f:
    new_data2 = pickle.load(f)

In [23]:
new_data2

[1, 1.2, 'a', 'b']

In [24]:
#erasing files
os.remove(os.path.join(datapath, 'data.pkl.gz'))
os.remove(os.path.join(datapath, 'data.pkl'))

## Acessing CSV Files

In [25]:
csvfile = "fakedata.csv"
datafile = os.path.join(datapath, csvfile)

#### Using pure Python:

In [26]:
data = []
with open(datafile, "r") as f:
    keys = f.readline().split('|')
    keys = [k.strip() for k in keys]
    for i in range(5):
        values = f.readline().split('|')
        values = [v.strip() for v in values]
        d = dict(zip(keys,values))
        data.append(d)
data[0:5]

[{'name': 'Fatima',
  'email': 'Quisque.varius@Integervitae.org',
  'birthdate': '11-25-01'},
 {'name': 'Katelyn',
  'email': 'mi.pede.nonummy@Sedid.ca',
  'birthdate': '11-27-03'},
 {'name': 'Gillian',
  'email': 'odio.semper@sodalesMaurisblandit.org',
  'birthdate': '02-19-14'},
 {'name': 'Preston',
  'email': 'faucibus.orci@lacusQuisque.edu',
  'birthdate': '08-07-09'},
 {'name': 'Priscilla',
  'email': 'semper.auctor@cursusvestibulum.co.uk',
  'birthdate': '08-12-01'}]

#### Using [CSV](https://docs.python.org/3/library/csv.html) module:

In [27]:
import csv

In [28]:
with open(datafile, "r") as f:
    data2 = csv.reader(f, delimiter='|')
    #data2 = csv.DictReader(f, delimiter='|')
    for row in data2:
        print(row)

['name', 'email', 'birthdate']
['Fatima', 'Quisque.varius@Integervitae.org', '11-25-01']
['Katelyn', 'mi.pede.nonummy@Sedid.ca', '11-27-03']
['Gillian', 'odio.semper@sodalesMaurisblandit.org', '02-19-14']
['Preston', 'faucibus.orci@lacusQuisque.edu', '08-07-09']
['Priscilla', 'semper.auctor@cursusvestibulum.co.uk', '08-12-01']
['Zena', 'ante@magnaPraesent.com', '11-24-11']
['Oren', 'rutrum.eu.ultrices@nec.org', '01-12-07']
['Jamalia', 'Phasellus.vitae.mauris@vel.org', '05-17-17']
['Libby', 'velit.eu@Maecenasmi.edu', '07-29-17']
['Finn', 'natoque.penatibus@lectusa.net', '06-23-10']
['Graiden', 'neque.Nullam@hendreritidante.com', '09-18-10']
['Kitra', 'quis.tristique@estmollis.com', '11-18-02']
['Baxter', 'vitae.mauris@sed.org', '04-12-17']
['Margaret', 'ullamcorper@nec.ca', '08-16-04']
['Sopoline', 'vitae.diam@velitQuisquevarius.co.uk', '09-03-06']
['Flynn', 'eget.varius@magnased.org', '08-28-14']
['Beck', 'arcu.et.pede@idblandit.co.uk', '01-14-06']
['Sheila', 'natoque.penatibus.et@matt

#### Using Pandas:

In [29]:
df_csv = pd.read_csv(datafile, sep="|")
df_csv.head()

name                                 email birthdate
0     Fatima       Quisque.varius@Integervitae.org  11-25-01
1    Katelyn              mi.pede.nonummy@Sedid.ca  11-27-03
2    Gillian  odio.semper@sodalesMaurisblandit.org  02-19-14
3    Preston        faucibus.orci@lacusQuisque.edu  08-07-09
4  Priscilla  semper.auctor@cursusvestibulum.co.uk  08-12-01

In [30]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   name       100 non-null    object
 1   email      100 non-null    object
 2   birthdate  100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB


## Manipulating [Zip Files](https://docs.python.org/3/library/zipfile.html)

In [31]:
from zipfile import ZipFile

#### CSV Files with Pandas

In [38]:
compressedfile = "HousingPrices.zip"
datafile = os.path.join(datapath, compressedfile)

In [45]:
pd_csv_zipped = pd.read_csv(datafile, compression='zip', engine='python')
pd_csv_zipped.head()

TransactionDate  HouseAge  DistanceToMRT  NumStores  Latitude  Longitude  \
0             2012      32.0       84.87882         10  24.98298  121.54024   
1             2012      19.5      306.59470          9  24.98034  121.53951   
2             2013      13.3      561.98450          5  24.98746  121.54391   
3             2013      13.3      561.98450          5  24.98746  121.54391   
4             2012       5.0      390.56840          5  24.97937  121.54245   

   UnitPrice  
0       37.9  
1       42.2  
2       47.3  
3       54.8  
4       43.1

#### XLS files with Pandas and Zipfile

In [56]:
compressedfile = "2013_ERCOT_Hourly_Load_Data.zip"
datafile = os.path.join(datapath, compressedfile)

In [58]:
with ZipFile(datafile, 'r') as myzip:
    print(myzip.namelist())
    unzipped = myzip.namelist()[0]
    with myzip.open(unzipped, 'r') as myfile:
        pd_excel = pd.read_excel(myfile)
        
pd_excel.head()

['2013_ERCOT_Hourly_Load_Data.xls']


Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0 2013-01-01 01:00:00  7606.263544  1073.892438  1411.750567  784.978166   
1 2013-01-01 02:00:00  7388.082714  1035.021938  1403.472287  776.307387   
2 2013-01-01 03:00:00  7178.867878  1036.088697  1395.053150  768.125748   
3 2013-01-01 04:00:00  7038.822581  1032.648841  1395.508820  770.937969   
4 2013-01-01 05:00:00  6990.857940  1042.823044  1401.216842  779.089313   

        NORTH_C     SOUTHERN      SOUTH_C        WEST         ERCOT  
0  10369.094390  2206.675077  4368.490945  882.931901  28704.077028  
1  10152.358518  2159.733208  4233.587967  872.404750  28020.968769  
2   9988.051418  2065.114706  4082.862860  868.853938  27383.018395  
3   9946.658655  1990.903699  4010.489608  865.701201  27051.671374  
4  10096.664190  1954.807585  4038.655997  879.924249  27184.039160

## [Acessing](https://pypi.python.org/pypi/xlrd) and [Writing](https://pypi.python.org/pypi/xlwt) [Excel Files](https://github.com/python-excel/tutorial/blob/master/python-excel.pdf)

In [59]:
#!sudo pip install -U xlrd xlwt

#### Accessing a workbook

In [60]:
import xlrd

In [61]:
with ZipFile(datafile, 'r') as myzip:
    unzipped = myzip.namelist()[0]
    myzip.extractall(datapath)

In [62]:
workbook = xlrd.open_workbook(os.path.join(datapath, unzipped))
sheet = workbook.sheet_by_index(0)

In [63]:
sheet_data = [[sheet.cell_value(r, col) for col in range(sheet.ncols)] for r in range(sheet.nrows)]
sheet_data[:2]

[['Hour_End',
  'COAST',
  'EAST',
  'FAR_WEST',
  'NORTH',
  'NORTH_C',
  'SOUTHERN',
  'SOUTH_C',
  'WEST',
  'ERCOT'],
 [41275.041666666664,
  7606.263544000012,
  1073.892438,
  1411.7505669999982,
  784.9781659999992,
  10369.094390000051,
  2206.6750770000012,
  4368.490945000006,
  882.9319009999975,
  28704.077028000065]]

In [64]:
print("Number of rows in the sheet:"),
print(sheet.nrows)

Number of rows in the sheet:
7296


In [65]:
print("Type of data in cell (row 3, col 2):"), 
print(sheet.cell_type(3, 2))

Type of data in cell (row 3, col 2):
2


In [66]:
print("Value in cell (row 3, col 2):", )
print(sheet.cell_value(3, 2))

Value in cell (row 3, col 2):
1036.0886969999988


In [67]:
print("Get a slice of values in column 3, from rows 1-3:",)
print(sheet.col_values(3, start_rowx=1, end_rowx=4))

Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]


In [68]:
coast = sheet.col_values(1, start_rowx=1)
data3 = {}    
data3['maxvalue'] = max(coast)
data3['minvalue'] = min(coast)
data3['avgcoast'] = np.mean(coast)

rowmax = coast.index(max(coast))+1
rowmin = coast.index(min(coast))+1

data3['maxtime'] = xlrd.xldate_as_tuple(sheet.cell_value(rowmax,0), 0)
data3['mintime'] = xlrd.xldate_as_tuple(sheet.cell_value(rowmin,0), 0)

In [69]:
data3

{'maxvalue': 18779.025510000003,
 'minvalue': 6602.113898999982,
 'avgcoast': 10976.933460679784,
 'maxtime': (2013, 8, 13, 17, 0, 0),
 'mintime': (2013, 2, 3, 4, 0, 0)}

#### Using Pandas

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html  

In [70]:
pd_excel = pd.read_excel(os.path.join(datapath, unzipped))
pd_excel.head()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0 2013-01-01 01:00:00  7606.263544  1073.892438  1411.750567  784.978166   
1 2013-01-01 02:00:00  7388.082714  1035.021938  1403.472287  776.307387   
2 2013-01-01 03:00:00  7178.867878  1036.088697  1395.053150  768.125748   
3 2013-01-01 04:00:00  7038.822581  1032.648841  1395.508820  770.937969   
4 2013-01-01 05:00:00  6990.857940  1042.823044  1401.216842  779.089313   

        NORTH_C     SOUTHERN      SOUTH_C        WEST         ERCOT  
0  10369.094390  2206.675077  4368.490945  882.931901  28704.077028  
1  10152.358518  2159.733208  4233.587967  872.404750  28020.968769  
2   9988.051418  2065.114706  4082.862860  868.853938  27383.018395  
3   9946.658655  1990.903699  4010.489608  865.701201  27051.671374  
4  10096.664190  1954.807585  4038.655997  879.924249  27184.039160

In [71]:
#erasing file
os.remove(os.path.join(datapath, unzipped))

#### Reading and Writing a Workbook

In [72]:
import xlwt

In [73]:
style0 = xlwt.easyxf('font: name Times New Roman, color-index red, bold on', num_format_str='#,##0.00')
style1 = xlwt.easyxf(num_format_str='D-MMM-YY')

In [74]:
workbook = xlwt.Workbook()
workbook_name = 'my_workbook.xls'

worksheet1 = workbook.add_sheet('my_first_sheet')
worksheet1.write(0, 0, 'Column 1 title', style0)
worksheet1.write(0, 1, 'Column 2 title', style0)

worksheet2 = workbook.add_sheet('my_second_sheet')
worksheet2.write(0, 0, 'Itens')
worksheet2.write(0, 1, 'Price')
worksheet2.write(1, 0, 'Rice')
worksheet2.write(1, 1, 100)
worksheet2.write(2, 0, 'Beans')
worksheet2.write(2, 1, 200)
worksheet2.write(3, 0, 'Pasta')
worksheet2.write(3, 1, 500)
worksheet2.write(5, 0, 'Total')

worksheet2.write(5, 1, xlwt.Formula("B2+B3+B4"))


workbook.save(os.path.join(datapath, workbook_name))

In [75]:
#erasing file
os.remove(os.path.join(datapath, workbook_name))

### Reading PDF Files  

More resources [here](https://textract.readthedocs.io/en/stable/) and [here](https://towardsdatascience.com/python-for-pdf-ef0fac2808b0?)

In [76]:
#!sudo pip install -U textract

In [77]:
import textract

In [78]:
onlyfiles = [f for f in os.listdir(datapath) if os.path.isfile(os.path.join(datapath, f)) and f.endswith('.pdf')]
onlyfiles.sort()

print('Files in the folder:')
for i, w in enumerate(onlyfiles):
    print(i, '--' ,w)

Files in the folder:
0 -- 1369576221wpdm_DVD Rental ER Diagram.pdf
1 -- RobertFrost_Poetry.pdf


In [79]:
text0 = textract.process(os.path.join(datapath, onlyfiles[0])).decode('utf-8')
print(text0[0:1000])

POSTGRESQL
TUTORIAL.COM

DVD Rental ER Diagram




### Reading Text in Image Files (OCR)

In [80]:
# !sudo apt install -y tesseract-ocr

In [81]:
onlyfiles = [f for f in os.listdir(datapath) if os.path.isfile(os.path.join(datapath, f)) and f.endswith('.png')]
onlyfiles.sort()

print('Files in the folder:')
for i, w in enumerate(onlyfiles):
    print(i, '--' ,w)

Files in the folder:
0 -- 1 HgrHDlU85dKtyLonNgu2zA.png
1 -- SQLAlchemyORM.png
2 -- db_schema.png
3 -- textimage.png


In [82]:
text1 = textract.process(os.path.join(datapath, onlyfiles[3])).decode('utf-8')

print(text1[0:900])

Adobe, the Adobe logo, Acrobat, the Acrobat logo, Acrobat Capture, Adobe Garamond, Adobe
Intelligent Document Platform, Adobe PDF, Adobe Reader, Adobe Solutions Network, Aldus, Dis-
tiller, ePaper, Extreme, FrameMaker, Illustrator, InDesign, Minion, Myriad, PageMaker, Photo-
shop, Poetica, PostScript, and XMP are either registered trademarks or trademarks of Adobe
‘Systems Incorporated in the United States and/or other countries. Microsoft and Windows are
either registered trademarks or trademarks of Microsoft Corporation in the United States and/or
other countries. Apple, Mac, Macintosh, and Power Macintosh are trademarks of Apple Computer,
Inc,, registered in the United States and other countries. IBM is a registered trademark of IBM
Corporation in the United States. Sun is a trademark or registered trademark of Sun Microsys-
tems, Inc. in the United States and other countries. UNIX is


## Accessing HTML

https://docs.python.org/3/library/urllib.html  
http://www.crummy.com/software/BeautifulSoup/  
http://docs.python-requests.org/en/latest/  
http://lxml.de/  
https://docs.python.org/3/library/getpass.html  

In [83]:
import urllib
import requests

from bs4 import BeautifulSoup as bs
import lxml.html

import getpass

In [84]:
url = "https://pt.wikipedia.org/wiki/Guimar%C3%A3es_Rosa"
html_txt = urllib.request.urlopen(url).read()
soup = bs(html_txt, "html.parser")
 
print(soup.text[0:300])





Guimarães Rosa – Wikipédia, a enciclopédia livre
document.documentElement.className="client-js";RLCONF={"wgBreakFrames":!1,"wgSeparatorTransformTable":[",\t."," \t,"],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","janeiro","fevereiro","março","abril","maio","junh


In [85]:
[line.get('href') for line in soup.find_all('a')][0:10] 

[None,
 '#mw-head',
 '#searchInput',
 '/wiki/Ficheiro:Guimar%C3%A3es_Rosa,_anos_1960.tif',
 '/wiki/Arquivo_Nacional_(Brasil)',
 '/wiki/27_de_junho#Nascimentos',
 '/wiki/1908',
 '/wiki/Cordisburgo',
 '/wiki/Minas_Gerais',
 '/wiki/19_de_novembro']

#### Another approach: [lxml](http://lxml.de/tutorial.html) instead of beautiful soup
 

In [86]:
url = "https://pt.wikipedia.org/wiki/Guimar%C3%A3es_Rosa"
html_txt = urllib.request.urlopen(url).read()
dom =  lxml.html.fromstring(html_txt)
    
[line for line in dom.xpath('//a/@href')][0:10]   

['#mw-head',
 '#searchInput',
 '/wiki/Ficheiro:Guimar%C3%A3es_Rosa,_anos_1960.tif',
 '/wiki/Arquivo_Nacional_(Brasil)',
 '/wiki/27_de_junho#Nascimentos',
 '/wiki/1908',
 '/wiki/Cordisburgo',
 '/wiki/Minas_Gerais',
 '/wiki/19_de_novembro',
 '/wiki/1967']

## Accessing [JSON](http://json.org/)

https://docs.python.org/3/library/json.html  
https://docs.python.org/3/library/urllib.html  

In [95]:
import json

In [96]:
base_url = "http://musicbrainz.org/ws/2/"
artist_url =  urllib.parse.urljoin(base_url, 'artist/')
query_type = {"simple": {},
              "atr": {"inc": "aliases+tags+ratings"},
              "aliases": {"inc": "aliases"},
              "releases": {"inc": "releases"}}

In [97]:
def query_site(url, params, uid="", fmt="json"):
    params["fmt"] = fmt
    r = requests.get(url + uid, params=params)
    print("requesting", r.url)

    if r.status_code == requests.codes.ok:
        return r.json()
    else:
        r.raise_for_status()

In [98]:
def query_by_name(url, params, name):
    params["query"] = "artist:" + name
    return query_site(url, params)

In [99]:
def pretty_print(data, indent=4):
    if type(data) == dict:
        print(json.dumps(data, indent=indent, sort_keys=True))
    else:
        print(data)

In [100]:
results = query_by_name(artist_url, query_type["simple"], "Nirvana")
pretty_print(results['artists'])  ##format

requesting http://musicbrainz.org/ws/2/artist/?query=artist%3ANirvana&fmt=json
[{'id': '5b11f4ce-a62d-471e-81fc-a69a8278c7da', 'type': 'Group', 'type-id': 'e431f5f6-b5d2-343d-8b36-72607fffb74b', 'score': 100, 'name': 'Nirvana', 'sort-name': 'Nirvana', 'country': 'US', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'United States', 'sort-name': 'United States', 'life-span': {'ended': None}}, 'begin-area': {'id': 'a640b45c-c173-49b1-8030-973603e895b5', 'type': 'City', 'type-id': '6fd8f29a-3d0a-32fc-980d-ea697b69da78', 'name': 'Aberdeen', 'sort-name': 'Aberdeen', 'life-span': {'ended': None}}, 'disambiguation': '90s US grunge band', 'isnis': ['0000000123486830', '0000000123487390'], 'life-span': {'begin': '1988-01', 'end': '1994-04-05', 'ended': True}, 'aliases': [{'sort-name': 'ニルヴァーナ', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'ニルヴァーナ', 'locale': 'ja', 'type': 'Artist name', 'primary':

In [101]:
results.keys()

dict_keys(['created', 'count', 'offset', 'artists'])

In [102]:
print("\nARTIST:")
pretty_print(results["artists"][0])


ARTIST:
{
    "aliases": [
        {
            "begin-date": null,
            "end-date": null,
            "locale": "ja",
            "name": "\u30cb\u30eb\u30f4\u30a1\u30fc\u30ca",
            "primary": true,
            "sort-name": "\u30cb\u30eb\u30f4\u30a1\u30fc\u30ca",
            "type": "Artist name",
            "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc"
        },
        {
            "begin-date": null,
            "end-date": null,
            "locale": null,
            "name": "Nirvana US",
            "primary": null,
            "sort-name": "Nirvana US",
            "type": null
        },
        {
            "begin-date": null,
            "end-date": null,
            "locale": "en",
            "name": "Nirvana",
            "primary": true,
            "sort-name": "Nirvana",
            "type": "Artist name",
            "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc"
        }
    ],
    "area": {
        "id": "489ce91b-6658-3307-9877-795b68554

In [103]:
artist_id = results["artists"][0]["id"]
artist_id

'5b11f4ce-a62d-471e-81fc-a69a8278c7da'

In [104]:
artist_data = query_site(artist_url, query_type["releases"], artist_id)
releases = artist_data["releases"]
print("\nONE RELEASE:")
pretty_print(releases[0], indent=2)

requesting http://musicbrainz.org/ws/2/artist/5b11f4ce-a62d-471e-81fc-a69a8278c7da?inc=releases&fmt=json

ONE RELEASE:
{
  "barcode": null,
  "country": "US",
  "date": "1988-11",
  "disambiguation": "",
  "id": "2c84c9b3-d1d4-48c0-a825-a360f26a5dde",
  "packaging": null,
  "packaging-id": null,
  "quality": "normal",
  "release-events": [
    {
      "area": {
        "disambiguation": "",
        "id": "489ce91b-6658-3307-9877-795b68554c98",
        "iso-3166-1-codes": [
          "US"
        ],
        "name": "United States",
        "sort-name": "United States",
        "type": null,
        "type-id": null
      },
      "date": "1988-11"
    }
  ],
  "status": "Official",
  "status-id": "4e304316-386d-3409-af2e-78857eec5cfe",
  "text-representation": {
    "language": "eng",
    "script": "Latn"
  },
  "title": "Love Buzz / Big Cheese"
}


In [105]:
releases

[{'date': '1988-11',
  'id': '2c84c9b3-d1d4-48c0-a825-a360f26a5dde',
  'packaging': None,
  'release-events': [{'date': '1988-11',
    'area': {'type-id': None,
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'iso-3166-1-codes': ['US'],
     'disambiguation': '',
     'sort-name': 'United States',
     'name': 'United States',
     'type': None}}],
  'disambiguation': '',
  'status': 'Official',
  'text-representation': {'language': 'eng', 'script': 'Latn'},
  'quality': 'normal',
  'packaging-id': None,
  'barcode': None,
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'country': 'US',
  'title': 'Love Buzz / Big Cheese'},
 {'release-events': [{'date': '1989-06-01',
    'area': {'disambiguation': '',
     'id': '489ce91b-6658-3307-9877-795b68554c98',
     'type-id': None,
     'iso-3166-1-codes': ['US'],
     'type': None,
     'sort-name': 'United States',
     'name': 'United States'}}],
  'status': 'Official',
  'disambiguation': '',
  'date': '1989-06-01',
  'id':

In [106]:
release_titles = [r["title"] for r in releases]
print("\nALL TITLES:")
for t in release_titles:
        print(t)


ALL TITLES:
Love Buzz / Big Cheese
Bleach
Bleach
Bleach
Bleach
Blew
Blew
Bleach
Bleach
Never Mind the Bollocks Here’s Nirvana
Sliver
Sliver
Sliver
Bleach
Bleach
Sliver
Sliver
Candy / Molly’s Lips
Here She Comes Now / Venus in Furs
Smells Like Teen Spirit
Smells Like Teen Spirit
Smells Like Teen Spirit
Smells Like Teen Spirit
Smells Like Teen Spirit
Smells Like Teen Spirit


#### Using Pandas

http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader  

In [107]:
df_json = pd.read_json('https://api.github.com/repos/pydata/pandas/issues?per_page=5')
df_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype              
---  ------                    --------------  -----              
 0   url                       5 non-null      object             
 1   repository_url            5 non-null      object             
 2   labels_url                5 non-null      object             
 3   comments_url              5 non-null      object             
 4   events_url                5 non-null      object             
 5   html_url                  5 non-null      object             
 6   id                        5 non-null      int64              
 7   node_id                   5 non-null      object             
 8   number                    5 non-null      int64              
 9   title                     5 non-null      object             
 10  user                      5 non-null      object             
 11  labels                 

In [108]:
df_json.title.head()

0    BUG: Setting a MultiIndex through set_index wh...
1    Revert "REF: back IntervalArray by a single nd...
2                             QST: Pandas without MKL?
3                     STYLE use types_or in pre-commit
4      ENH: support 2D in DatetimeArray._from_sequence
Name: title, dtype: object

## Accessing YAML

In [109]:
import yaml

In [110]:
with open(os.path.join(datapath, 'simple.yaml'), 'r') as stream:
    try:
        yamlfile = yaml.load(stream, Loader=yaml.Loader)
        print(yamlfile)
    except yaml.YAMLError as exc:
        print(exc)

[{'martin': {'name': "Martin D'vloper", 'job': 'Developer', 'skills': ['python', 'perl', 'pascal']}}, {'tabitha': {'name': 'Tabitha Bitumen', 'job': 'Developer', 'skills': ['lisp', 'fortran', 'erlang']}}]


In [111]:
pd.DataFrame(yamlfile[0])

martin
job                  Developer
name           Martin D'vloper
skills  [python, perl, pascal]

## Accessing XML

https://docs.python.org/3/library/urllib.html

https://docs.python.org/3/library/xml.etree.elementtree.html

http://lxml.de/

http://www.w3schools.com/xml/xml_examples.asp

In [112]:
from xml.dom import minidom
#from xml.etree import ElementTree as ET
from lxml import etree as ET #Supports xpath syntax
from collections import defaultdict
from pprint import pprint

In [113]:
url = 'http://www.w3schools.com/xml/cd_catalog.xml'
xml_page = urllib.request.urlopen(url).read()
e = ET.XML(xml_page)

In [114]:
def etree_to_dict(t):
    d = {t.tag: {} if t.attrib else None}
    children = list(t)
    if children:
        dd = defaultdict(list)
        for dc in map(etree_to_dict, children):
            for k, v in dc.items():
                dd[k].append(v)
        d = {t.tag: {k:v[0] if len(v) == 1 else v for k, v in dd.items()}}
    if t.attrib:
        d[t.tag].update(('@' + k, v) for k, v in t.attrib.items())
    if t.text:
        text = t.text.strip()
        if children or t.attrib:
            if text:
              d[t.tag]['#text'] = text
        else:
            d[t.tag] = text
    return d

In [115]:
pprint(etree_to_dict(e))

{'CATALOG': {'CD': [{'ARTIST': 'Bob Dylan',
                     'COMPANY': 'Columbia',
                     'COUNTRY': 'USA',
                     'PRICE': '10.90',
                     'TITLE': 'Empire Burlesque',
                     'YEAR': '1985'},
                    {'ARTIST': 'Bonnie Tyler',
                     'COMPANY': 'CBS Records',
                     'COUNTRY': 'UK',
                     'PRICE': '9.90',
                     'TITLE': 'Hide your heart',
                     'YEAR': '1988'},
                    {'ARTIST': 'Dolly Parton',
                     'COMPANY': 'RCA',
                     'COUNTRY': 'USA',
                     'PRICE': '9.90',
                     'TITLE': 'Greatest Hits',
                     'YEAR': '1982'},
                    {'ARTIST': 'Gary Moore',
                     'COMPANY': 'Virgin records',
                     'COUNTRY': 'UK',
                     'PRICE': '10.20',
                     'TITLE': 'Still got the blues',
                

In [116]:
raw_page = urllib.request.urlopen(url)
doc = minidom.parse(raw_page)

def findTextnodes(nodeList):
    for subnode in nodeList:
        if subnode.nodeType == subnode.ELEMENT_NODE:
            print("Element node: " + subnode.tagName)
            findTextnodes(subnode.childNodes)
        elif subnode.nodeType == subnode.TEXT_NODE:
            print("text node:" + subnode.data)
            
findTextnodes(doc.childNodes)

Element node: CATALOG
text node:
  
Element node: CD
text node:
    
Element node: TITLE
text node:Empire Burlesque
text node:
    
Element node: ARTIST
text node:Bob Dylan
text node:
    
Element node: COUNTRY
text node:USA
text node:
    
Element node: COMPANY
text node:Columbia
text node:
    
Element node: PRICE
text node:10.90
text node:
    
Element node: YEAR
text node:1985
text node:
  
text node:
  
Element node: CD
text node:
    
Element node: TITLE
text node:Hide your heart
text node:
    
Element node: ARTIST
text node:Bonnie Tyler
text node:
    
Element node: COUNTRY
text node:UK
text node:
    
Element node: COMPANY
text node:CBS Records
text node:
    
Element node: PRICE
text node:9.90
text node:
    
Element node: YEAR
text node:1988
text node:
  
text node:
  
Element node: CD
text node:
    
Element node: TITLE
text node:Greatest Hits
text node:
    
Element node: ARTIST
text node:Dolly Parton
text node:
    
Element node: COUNTRY
text node:USA
text node:
    
Elem

In [117]:
root = ET.fromstring(xml_page)
cdtags = root.xpath('//CD/TITLE')
for cd in cdtags:
    print(cd.text)

Empire Burlesque
Hide your heart
Greatest Hits
Still got the blues
Eros
One night only
Sylvias Mother
Maggie May
Romanza
When a man loves a woman
Black angel
1999 Grammy Nominees
For the good times
Big Willie style
Tupelo Honey
Soulsville
The very best of
Stop
Bridge of Spies
Private Dancer
Midt om natten
Pavarotti Gala Concert
The dock of the bay
Picture book
Red
Unchain my heart


In [118]:
for cd in root.findall('CD'):
    title = cd.find('TITLE').text
    artist = cd.find('ARTIST').text
    country = cd.find('COUNTRY').text
    print('{}\t{}\t{}'.format(artist, country, title))

Bob Dylan	USA	Empire Burlesque
Bonnie Tyler	UK	Hide your heart
Dolly Parton	USA	Greatest Hits
Gary Moore	UK	Still got the blues
Eros Ramazzotti	EU	Eros
Bee Gees	UK	One night only
Dr.Hook	UK	Sylvias Mother
Rod Stewart	UK	Maggie May
Andrea Bocelli	EU	Romanza
Percy Sledge	USA	When a man loves a woman
Savage Rose	EU	Black angel
Many	USA	1999 Grammy Nominees
Kenny Rogers	UK	For the good times
Will Smith	USA	Big Willie style
Van Morrison	UK	Tupelo Honey
Jorn Hoel	Norway	Soulsville
Cat Stevens	UK	The very best of
Sam Brown	UK	Stop
T'Pau	UK	Bridge of Spies
Tina Turner	UK	Private Dancer
Kim Larsen	EU	Midt om natten
Luciano Pavarotti	UK	Pavarotti Gala Concert
Otis Redding	USA	The dock of the bay
Simply Red	EU	Picture book
The Communards	UK	Red
Joe Cocker	USA	Unchain my heart


In [119]:
cds = []
for cd in root.findall('./CD'):
        data = {}
        data["TITLE"] = cd.find('./TITLE').text
        data["ARTIST"] = cd.find('./ARTIST').text
        data["COUNTRY"] = cd.find('./COUNTRY').text
        data["PRICE"] = cd.find('./PRICE').text
        data["YEAR"] = cd.find('./YEAR').text
        cds.append(data)
cds[0:3]

[{'TITLE': 'Empire Burlesque',
  'ARTIST': 'Bob Dylan',
  'COUNTRY': 'USA',
  'PRICE': '10.90',
  'YEAR': '1985'},
 {'TITLE': 'Hide your heart',
  'ARTIST': 'Bonnie Tyler',
  'COUNTRY': 'UK',
  'PRICE': '9.90',
  'YEAR': '1988'},
 {'TITLE': 'Greatest Hits',
  'ARTIST': 'Dolly Parton',
  'COUNTRY': 'USA',
  'PRICE': '9.90',
  'YEAR': '1982'}]

## Accessing Feeds RSS

http://www.feedparser.org/  
http://docs.python.org/library/re.html  
http://www.pythonware.com/library/pil/handbook/index.htm  

In [120]:
import feedparser

In [121]:
d = feedparser.parse('https://oglobo.globo.com/rss.xml')

In [122]:
print(d['feed']['title'])
print(d['feed']['link'])
#print(d.feed.subtitle)
print(len(d['entries']))

OGlobo
https://oglobo.globo.com/
10


In [123]:
print(d['entries'][0]['title']) 
print(d.entries[0]['link'])

Congresso da Guatemala suspende aprovação de Orçamento, mas medida não deve acalmar protestos
https://oglobo.globo.com/mundo/congresso-da-guatemala-suspende-aprovacao-de-orcamento-mas-medida-nao-deve-acalmar-protestos-24761271


In [124]:
print(d.headers)

{'Date': 'Mon, 23 Nov 2020 22:54:22 GMT', 'Server': 'Apache', 'Referrer-Policy': 'no-referrer-when-downgrade', 'Feature-Policy': "geolocation 'none'; midi 'none'; microphone 'none'; camera 'none'; speaker 'self'; fullscreen 'self';", 'X-Frame-Options': 'SAMEORIGIN', 'Expires': '1606172072146', 'Content-Type': 'application/rss+xml;charset=UTF-8', 'Access-Control-Allow-Origin': '*', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'Content-Length': '2881', 'cache-control': 'public, max-age=602', 'Age': '0', 'grace': 'none', 'X-Cache': 'MISS', 'Accept-Ranges': 'bytes', 'Strict-Transport-Security': 'max-age=15768000', 'Content-Security-Policy': "default-src 'self' 'unsafe-inline' https: data: blob:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https: blob:; img-src 'self' data: https:;", 'X-XSS-Protection': '1; mode=block', 'Connection': 'close'}


In [125]:
for post in d.entries:
    print(post.title + ": " + post.link + "\n")

Congresso da Guatemala suspende aprovação de Orçamento, mas medida não deve acalmar protestos: https://oglobo.globo.com/mundo/congresso-da-guatemala-suspende-aprovacao-de-orcamento-mas-medida-nao-deve-acalmar-protestos-24761271

Diante da pandemia, Correios criam canal digital para receber cartinhas para Papai Noel: https://oglobo.globo.com/rio/diante-da-pandemia-correios-criam-canal-digital-para-receber-cartinhas-para-papai-noel-1-24761611

Covid-19: em Niterói, novos casos batem recorde e ocupação de leitos quase dobra em um mês: https://oglobo.globo.com/rio/bairros/covid-19-em-niteroi-novos-casos-batem-recorde-ocupacao-de-leitos-quase-dobra-em-um-mes-24761596

Ex-presidente do Fed, keynesiana será nova secretária do Tesouro de Biden: https://oglobo.globo.com/mundo/ex-presidente-do-fed-keynesiana-sera-nova-secretaria-do-tesouro-de-biden-24761584

Senador pede que TCU apure estoque de 6,8 milhões de testes de Covid perto do vencimento: https://epoca.globo.com/guilherme-amado/senador-p

## Dealing with Big Files

Retrieving the file:

In [126]:
link = 'http://eforexcel.com/wp/wp-content/uploads/2017/07/1500000%20Sales%20Records.zip'
filename = "bigcsv.zip"

In [127]:
urllib.request.urlretrieve(link, os.path.join(datapath, filename))

('../SampleDBs/bigcsv.zip', <http.client.HTTPMessage at 0x7fe74fb52340>)

Using Pandas with chunks:

In [128]:
chunksize = 10 ** 5
num_chunks_to_read = 3

with ZipFile(os.path.join(datapath, filename), 'r') as myzip:
    print(myzip.namelist())
    unzipped = myzip.namelist()[0]
    with myzip.open(unzipped) as myfile:
        chunks = pd.read_csv((myfile), chunksize=chunksize) #, iterator=True)
        for i in range(num_chunks_to_read):
            print('Retrieving a new chunk')
            df = chunks.get_chunk()
            print(df.head(3))
            print()

['1500000 Sales Records.csv']
Retrieving a new chunk
                         Region           Country Item Type Sales Channel  \
0            Sub-Saharan Africa      South Africa    Fruits       Offline   
1  Middle East and North Africa           Morocco   Clothes        Online   
2         Australia and Oceania  Papua New Guinea      Meat       Offline   

  Order Priority Order Date   Order ID   Ship Date  Units Sold  Unit Price  \
0              M  7/27/2012  443368995   7/28/2012        1593        9.33   
1              M  9/14/2013  667593514  10/19/2013        4611      109.28   
2              M  5/15/2015  940995585    6/4/2015         360      421.89   

   Unit Cost  Total Revenue  Total Cost  Total Profit  
0       6.92       14862.69    11023.56       3839.13  
1      35.84      503890.08   165258.24     338631.84  
2     364.69      151880.40   131288.40      20592.00  

Retrieving a new chunk
                       Region      Country      Item Type Sales Channel  \
10

Unzipping the file and reading line by line:

In [129]:
with ZipFile(os.path.join(datapath, filename), 'r') as myzip:
    myzip.extractall(datapath)
    myzip.close()

In [130]:
def getstuff(filename):
    with open(filename, "r") as csvfile:
        datareader = csv.reader(csvfile)
        count = 0
        for row in datareader:
            yield(row)

In [131]:
count = 0
for row in getstuff(os.path.join(datapath, unzipped)):
    print(row)
    count +=1
    if count > 30:
        break

['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority', 'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price', 'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit']
['Sub-Saharan Africa', 'South Africa', 'Fruits', 'Offline', 'M', '7/27/2012', '443368995', '7/28/2012', '1593', '9.33', '6.92', '14862.69', '11023.56', '3839.13']
['Middle East and North Africa', 'Morocco', 'Clothes', 'Online', 'M', '9/14/2013', '667593514', '10/19/2013', '4611', '109.28', '35.84', '503890.08', '165258.24', '338631.84']
['Australia and Oceania', 'Papua New Guinea', 'Meat', 'Offline', 'M', '5/15/2015', '940995585', '6/4/2015', '360', '421.89', '364.69', '151880.40', '131288.40', '20592.00']
['Sub-Saharan Africa', 'Djibouti', 'Clothes', 'Offline', 'H', '5/17/2017', '880811536', '7/2/2017', '562', '109.28', '35.84', '61415.36', '20142.08', '41273.28']
['Europe', 'Slovakia', 'Beverages', 'Offline', 'L', '10/26/2016', '174590194', '12/4/2016', '3973', '47.45', '31.79', '188518.85'

In [132]:
#erasing files
os.remove(os.path.join(datapath, unzipped))
os.remove(os.path.join(datapath, filename))

## Using [HDF5](https://portal.hdfgroup.org/display/HDF5/HDF5)  

In [133]:
#!sudo pip install -q -U h5py  

In [134]:
import h5py

arr = np.random.randn(1000)

filename = 'random.hdf5'
#with h5py.File(os.path.join(datapath, filename), 'a') as f:   #if we'd like to append data
with h5py.File(os.path.join(datapath, filename), 'w') as f:
    dset = f.create_dataset("default", data=arr)

In [135]:
with h5py.File(os.path.join(datapath, filename), 'r') as f:
    for key in f.keys():
        print("datasets in ths hdf system:", key)
    
    data = f['default']
    print(type(data))
    print(min(data))
    print(max(data))
    print(data[:15])

datasets in ths hdf system: default
<class 'h5py._hl.dataset.Dataset'>
-3.479282889615609
3.6737890387306273
[-0.0733763   1.977096    2.68400541 -1.218146   -0.51492353 -0.20166485
  0.22468251  0.07396668  2.537742   -0.05775606 -0.21569235  0.55821857
 -0.12452188 -0.41375131  0.86207905]


In [136]:
arr1 = np.random.randn(10000)
arr2 = np.random.randn(10000)

with h5py.File(os.path.join(datapath, filename), 'w') as f:
    f.create_dataset('array_1', data=arr1)
    f.create_dataset('array_2', data=arr2)

In [137]:
with h5py.File(os.path.join(datapath, filename), 'r') as f:
    d1 = f['array_1']
    d2 = f['array_2']
    print(type(d1))
    print(type(d2))
    #data = d2[d1>0]  #error
    data = d2[d1[:]>0]
    print(data)

<class 'h5py._hl.dataset.Dataset'>
<class 'h5py._hl.dataset.Dataset'>
[-0.83647623 -0.63184235  0.66122518 ... -0.06135184  0.45004874
  1.24138489]


In [138]:
#erasing files

os.remove(os.path.join(datapath, filename))

### TBD

In [ ]:
#https://vaex.readthedocs.io/en/latest/

In [61]:
#https://docs.dask.org/en/latest/dataframe.html

In [ ]:
#https://www.markdownguide.org/cheat-sheet/