## Introduction to Databases

### Miscellaneous Formats

In [1]:
import os
import sys
import time
import datetime
import numpy as np
import pandas as pd

In [2]:
datapath = "../SampleDBs/"

## Saving a txt file

In [3]:
with open(os.path.join(datapath, 'newfile.txt'), mode='w', encoding='utf-8') as f:
    f.write('Weight\t\t72\n')
    f.write('Height\t\t183\n')
    f.write('Age\t\t44\n')
    f.write('Gender\t\tMasculine\n')
    f.write('\n')

## Retrieving a txt file

In [4]:
with open(os.path.join(datapath, 'newfile.txt'), mode='r', encoding='utf-8') as f:
    fulltext = f.read()
    f.seek(0)
    line = f.readline()
    f.seek(0)
    list_of_lines = f.readlines()

In [5]:
print(fulltext)

Weight		72
Height		183
Age		44
Gender		Masculine




In [6]:
print(line)

Weight		72



In [7]:
print(list_of_lines)

['Weight\t\t72\n', 'Height\t\t183\n', 'Age\t\t44\n', 'Gender\t\tMasculine\n', '\n']


In [8]:
#erasing file
os.remove(os.path.join(datapath, 'newfile.txt'))

## Saving Numpy Structures

In [9]:
data = np.linspace(0,1,201)
print(data)

[0.    0.005 0.01  0.015 0.02  0.025 0.03  0.035 0.04  0.045 0.05  0.055
 0.06  0.065 0.07  0.075 0.08  0.085 0.09  0.095 0.1   0.105 0.11  0.115
 0.12  0.125 0.13  0.135 0.14  0.145 0.15  0.155 0.16  0.165 0.17  0.175
 0.18  0.185 0.19  0.195 0.2   0.205 0.21  0.215 0.22  0.225 0.23  0.235
 0.24  0.245 0.25  0.255 0.26  0.265 0.27  0.275 0.28  0.285 0.29  0.295
 0.3   0.305 0.31  0.315 0.32  0.325 0.33  0.335 0.34  0.345 0.35  0.355
 0.36  0.365 0.37  0.375 0.38  0.385 0.39  0.395 0.4   0.405 0.41  0.415
 0.42  0.425 0.43  0.435 0.44  0.445 0.45  0.455 0.46  0.465 0.47  0.475
 0.48  0.485 0.49  0.495 0.5   0.505 0.51  0.515 0.52  0.525 0.53  0.535
 0.54  0.545 0.55  0.555 0.56  0.565 0.57  0.575 0.58  0.585 0.59  0.595
 0.6   0.605 0.61  0.615 0.62  0.625 0.63  0.635 0.64  0.645 0.65  0.655
 0.66  0.665 0.67  0.675 0.68  0.685 0.69  0.695 0.7   0.705 0.71  0.715
 0.72  0.725 0.73  0.735 0.74  0.745 0.75  0.755 0.76  0.765 0.77  0.775
 0.78  0.785 0.79  0.795 0.8   0.805 0.81  0.815 0.

In [10]:
np.savetxt(os.path.join(datapath, 'data.dat'), data)

In [11]:
new_data = np.loadtxt(os.path.join(datapath, 'data.dat'))
print(new_data)

[0.    0.005 0.01  0.015 0.02  0.025 0.03  0.035 0.04  0.045 0.05  0.055
 0.06  0.065 0.07  0.075 0.08  0.085 0.09  0.095 0.1   0.105 0.11  0.115
 0.12  0.125 0.13  0.135 0.14  0.145 0.15  0.155 0.16  0.165 0.17  0.175
 0.18  0.185 0.19  0.195 0.2   0.205 0.21  0.215 0.22  0.225 0.23  0.235
 0.24  0.245 0.25  0.255 0.26  0.265 0.27  0.275 0.28  0.285 0.29  0.295
 0.3   0.305 0.31  0.315 0.32  0.325 0.33  0.335 0.34  0.345 0.35  0.355
 0.36  0.365 0.37  0.375 0.38  0.385 0.39  0.395 0.4   0.405 0.41  0.415
 0.42  0.425 0.43  0.435 0.44  0.445 0.45  0.455 0.46  0.465 0.47  0.475
 0.48  0.485 0.49  0.495 0.5   0.505 0.51  0.515 0.52  0.525 0.53  0.535
 0.54  0.545 0.55  0.555 0.56  0.565 0.57  0.575 0.58  0.585 0.59  0.595
 0.6   0.605 0.61  0.615 0.62  0.625 0.63  0.635 0.64  0.645 0.65  0.655
 0.66  0.665 0.67  0.675 0.68  0.685 0.69  0.695 0.7   0.705 0.71  0.715
 0.72  0.725 0.73  0.735 0.74  0.745 0.75  0.755 0.76  0.765 0.77  0.775
 0.78  0.785 0.79  0.795 0.8   0.805 0.81  0.815 0.

In [12]:
#erasing file
os.remove(os.path.join(datapath, 'data.dat'))

In [13]:
x = np.linspace(0, 1, 20)
y = np.random.random(20)
header = "X-Column, Y-Column\n"
header += "This is a second line"

with open(os.path.join(datapath,'data2.dat'), 'wb') as f:
#with open(os.path.join(datapath,'data2.dat'), 'w') as f:   #using text formatting and no binary files
    np.savetxt(f, [], header=header)
    for i in range(20):
        data = np.column_stack((x[i], y[i]))
        np.savetxt(f, data), print(data)
        #f.write('{:4.1f} {:.4f}\n'.format(x[i], y[i]))    #using text formatting and no binary files
        f.flush()

[[0.         0.72865167]]
[[0.05263158 0.41424254]]
[[0.10526316 0.49498442]]
[[0.15789474 0.48065259]]
[[0.21052632 0.62067216]]
[[0.26315789 0.17738839]]
[[0.31578947 0.88995241]]
[[0.36842105 0.53264059]]
[[0.42105263 0.07352186]]
[[0.47368421 0.3772164 ]]
[[0.52631579 0.12462665]]
[[0.57894737 0.86828776]]
[[0.63157895 0.15304811]]
[[0.68421053 0.73725966]]
[[0.73684211 0.13985777]]
[[0.78947368 0.00639617]]
[[0.84210526 0.73638896]]
[[0.89473684 0.00628633]]
[[0.94736842 0.93772871]]
[[1.         0.09788498]]


In [14]:
! cat ../SampleDBs/data2.dat

# X-Column, Y-Column
# This is a second line
0.000000000000000000e+00 7.286516700066931751e-01
5.263157894736841813e-02 4.142425368454596413e-01
1.052631578947368363e-01 4.949844234341568283e-01
1.578947368421052544e-01 4.806525853568911488e-01
2.105263157894736725e-01 6.206721584287625548e-01
2.631578947368420907e-01 1.773883900160257987e-01
3.157894736842105088e-01 8.899524059386328956e-01
3.684210526315789269e-01 5.326405881450090307e-01
4.210526315789473450e-01 7.352186366627488923e-02
4.736842105263157632e-01 3.772163983115532915e-01
5.263157894736841813e-01 1.246266486754834535e-01
5.789473684210526550e-01 8.682877608836656602e-01
6.315789473684210176e-01 1.530481090532087585e-01
6.842105263157893802e-01 7.372596557228354719e-01
7.368421052631578538e-01 1.398577713315550808e-01
7.894736842105263275e-01 6.396173138688232562e-03
8.421052631578946901e-01 7.363889607695421891e-01
8.947368421052630527e-01 6.286331248876897426e-03
9.473684210526315264e-01 9.377287104046299060e-01
1.000

In [15]:
#erasing file
os.remove(os.path.join(datapath, 'data2.dat'))

## Using Pickle

In [16]:
import pickle

data = [1, 1.2, 'a', 'b']

with open(os.path.join(datapath, 'data.pkl'), 'wb') as f:
    pickle.dump(data, f)

In [17]:
with open(os.path.join(datapath, 'data.pkl'), 'rb') as f:
    new_data = pickle.load(f)

print(new_data)

[1, 1.2, 'a', 'b']


In [18]:
#erasing file
os.remove(os.path.join(datapath, 'data.pkl'))

## Acessing CSV Files

In [19]:
csvfile = "fakedata.csv"
datafile = os.path.join(datapath, csvfile)

#### Using pure Python:

In [20]:
data = []
with open(datafile, "r") as f:
    keys = f.readline().split('|')
    keys = [k.strip() for k in keys]
    for i in range(5):
        values = f.readline().split('|')
        values = [v.strip() for v in values]
        d = dict(zip(keys,values))
        data.append(d)
data[0:2]

[{'name': 'Fatima',
  'email': 'Quisque.varius@Integervitae.org',
  'birthdate': '11-25-01'},
 {'name': 'Katelyn',
  'email': 'mi.pede.nonummy@Sedid.ca',
  'birthdate': '11-27-03'}]

#### Using [CSV](https://docs.python.org/3/library/csv.html) module:

In [21]:
import csv

In [22]:
with open(datafile, "r") as f:
    #data2 = csv.reader(f, delimiter='|')
    data2 = csv.DictReader(f, delimiter='|')
    for row in data2:
        print(row)

{'name': 'Fatima', 'email': 'Quisque.varius@Integervitae.org', 'birthdate': '11-25-01'}
{'name': 'Katelyn', 'email': 'mi.pede.nonummy@Sedid.ca', 'birthdate': '11-27-03'}
{'name': 'Gillian', 'email': 'odio.semper@sodalesMaurisblandit.org', 'birthdate': '02-19-14'}
{'name': 'Preston', 'email': 'faucibus.orci@lacusQuisque.edu', 'birthdate': '08-07-09'}
{'name': 'Priscilla', 'email': 'semper.auctor@cursusvestibulum.co.uk', 'birthdate': '08-12-01'}
{'name': 'Zena', 'email': 'ante@magnaPraesent.com', 'birthdate': '11-24-11'}
{'name': 'Oren', 'email': 'rutrum.eu.ultrices@nec.org', 'birthdate': '01-12-07'}
{'name': 'Jamalia', 'email': 'Phasellus.vitae.mauris@vel.org', 'birthdate': '05-17-17'}
{'name': 'Libby', 'email': 'velit.eu@Maecenasmi.edu', 'birthdate': '07-29-17'}
{'name': 'Finn', 'email': 'natoque.penatibus@lectusa.net', 'birthdate': '06-23-10'}
{'name': 'Graiden', 'email': 'neque.Nullam@hendreritidante.com', 'birthdate': '09-18-10'}
{'name': 'Kitra', 'email': 'quis.tristique@estmollis.

#### Using Pandas:

In [23]:
df_csv = pd.read_csv(datafile, sep="|")
df_csv.head()
#df_csv.info()

name                                 email birthdate
0     Fatima       Quisque.varius@Integervitae.org  11-25-01
1    Katelyn              mi.pede.nonummy@Sedid.ca  11-27-03
2    Gillian  odio.semper@sodalesMaurisblandit.org  02-19-14
3    Preston        faucibus.orci@lacusQuisque.edu  08-07-09
4  Priscilla  semper.auctor@cursusvestibulum.co.uk  08-12-01

## Manipulating [Zip Files](https://docs.python.org/3/library/zipfile.html)

In [24]:
from zipfile import ZipFile

In [25]:
compressedfile = "2013_ERCOT_Hourly_Load_Data.zip"
datafile = os.path.join(datapath, compressedfile)

In [26]:
with ZipFile(datafile, 'r') as myzip:
    print(myzip.namelist())
    unzipped = myzip.namelist()[0]
    with myzip.open(unzipped) as myfile:
        pd_excel = pd.read_excel(myfile)
        
pd_excel.head()

['2013_ERCOT_Hourly_Load_Data.xls']


Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0 2013-01-01 01:00:00  7606.263544  1073.892438  1411.750567  784.978166   
1 2013-01-01 02:00:00  7388.082714  1035.021938  1403.472287  776.307387   
2 2013-01-01 03:00:00  7178.867878  1036.088697  1395.053150  768.125748   
3 2013-01-01 04:00:00  7038.822581  1032.648841  1395.508820  770.937969   
4 2013-01-01 05:00:00  6990.857940  1042.823044  1401.216842  779.089313   

        NORTH_C     SOUTHERN      SOUTH_C        WEST         ERCOT  
0  10369.094390  2206.675077  4368.490945  882.931901  28704.077028  
1  10152.358518  2159.733208  4233.587967  872.404750  28020.968769  
2   9988.051418  2065.114706  4082.862860  868.853938  27383.018395  
3   9946.658655  1990.903699  4010.489608  865.701201  27051.671374  
4  10096.664190  1954.807585  4038.655997  879.924249  27184.039160

## [Acessing](https://pypi.python.org/pypi/xlrd) and [Writing](https://pypi.python.org/pypi/xlwt) [Excel Files](https://github.com/python-excel/tutorial/blob/master/python-excel.pdf)

In [27]:
#!sudo pip install -U xlrd xlwt

#### Accessing a workbook

In [28]:
import xlrd

In [29]:
with ZipFile(datafile, 'r') as myzip:
    unzipped = myzip.namelist()[0]
    myzip.extractall(datapath)

In [30]:
workbook = xlrd.open_workbook(os.path.join(datapath, unzipped))
sheet = workbook.sheet_by_index(0)

In [31]:
sheet_data = [[sheet.cell_value(r, col) for col in range(sheet.ncols)] for r in range(sheet.nrows)]
sheet_data[:2]

[['Hour_End',
  'COAST',
  'EAST',
  'FAR_WEST',
  'NORTH',
  'NORTH_C',
  'SOUTHERN',
  'SOUTH_C',
  'WEST',
  'ERCOT'],
 [41275.041666666664,
  7606.263544000012,
  1073.892438,
  1411.7505669999982,
  784.9781659999992,
  10369.094390000051,
  2206.6750770000012,
  4368.490945000006,
  882.9319009999975,
  28704.077028000065]]

In [32]:
print("Number of rows in the sheet:"),
print(sheet.nrows)

Number of rows in the sheet:
7296


In [33]:
print("Type of data in cell (row 3, col 2):"), 
print(sheet.cell_type(3, 2))

Type of data in cell (row 3, col 2):
2


In [34]:
print("Value in cell (row 3, col 2):", )
print(sheet.cell_value(3, 2))

Value in cell (row 3, col 2):
1036.0886969999988


In [35]:
print("Get a slice of values in column 3, from rows 1-3:",)
print(sheet.col_values(3, start_rowx=1, end_rowx=4))

Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]


In [36]:
coast = sheet.col_values(1, start_rowx=1)
data3 = {}    
data3['maxvalue'] = max(coast)
data3['minvalue'] = min(coast)
data3['avgcoast'] = np.mean(coast)

rowmax = coast.index(max(coast))+1
rowmin = coast.index(min(coast))+1

data3['maxtime'] = xlrd.xldate_as_tuple(sheet.cell_value(rowmax,0), 0)
data3['mintime'] = xlrd.xldate_as_tuple(sheet.cell_value(rowmin,0), 0)

In [37]:
data3

{'maxvalue': 18779.025510000003,
 'minvalue': 6602.113898999982,
 'avgcoast': 10976.933460679784,
 'maxtime': (2013, 8, 13, 17, 0, 0),
 'mintime': (2013, 2, 3, 4, 0, 0)}

#### Using Pandas

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html  

In [38]:
pd_excel = pd.read_excel(os.path.join(datapath, unzipped))
pd_excel.head()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0 2013-01-01 01:00:00  7606.263544  1073.892438  1411.750567  784.978166   
1 2013-01-01 02:00:00  7388.082714  1035.021938  1403.472287  776.307387   
2 2013-01-01 03:00:00  7178.867878  1036.088697  1395.053150  768.125748   
3 2013-01-01 04:00:00  7038.822581  1032.648841  1395.508820  770.937969   
4 2013-01-01 05:00:00  6990.857940  1042.823044  1401.216842  779.089313   

        NORTH_C     SOUTHERN      SOUTH_C        WEST         ERCOT  
0  10369.094390  2206.675077  4368.490945  882.931901  28704.077028  
1  10152.358518  2159.733208  4233.587967  872.404750  28020.968769  
2   9988.051418  2065.114706  4082.862860  868.853938  27383.018395  
3   9946.658655  1990.903699  4010.489608  865.701201  27051.671374  
4  10096.664190  1954.807585  4038.655997  879.924249  27184.039160

In [39]:
#erasing file
os.remove(os.path.join(datapath, unzipped))

#### Reading and Writing a Workbook

In [40]:
import xlwt

In [41]:
style0 = xlwt.easyxf('font: name Times New Roman, color-index red, bold on', num_format_str='#,##0.00')
style1 = xlwt.easyxf(num_format_str='D-MMM-YY')

In [42]:
workbook = xlwt.Workbook()
workbook_name = 'my_workbook.xls'

worksheet1 = workbook.add_sheet('my_first_sheet')
worksheet1.write(0, 0, 'Column 1 title', style0)
worksheet1.write(0, 1, 'Column 2 title', style0)

worksheet2 = workbook.add_sheet('my_second_sheet')
worksheet2.write(0, 0, 'Itens')
worksheet2.write(0, 1, 'Price')
worksheet2.write(1, 0, 'Rice')
worksheet2.write(1, 1, 100)
worksheet2.write(2, 0, 'Beans')
worksheet2.write(2, 1, 200)
worksheet2.write(3, 0, 'Pasta')
worksheet2.write(3, 1, 500)
worksheet2.write(5, 0, 'Total')

worksheet2.write(5, 1, xlwt.Formula("B2+B3+B4"))


workbook.save(os.path.join(datapath, workbook_name))

In [43]:
#erasing file
os.remove(os.path.join(datapath, workbook_name))

### Reading PDF Files  

More resources [here](https://textract.readthedocs.io/en/stable/) and [here](https://towardsdatascience.com/python-for-pdf-ef0fac2808b0?)

In [44]:
#!sudo pip install -U textract

In [45]:
import textract

In [46]:
onlyfiles = [f for f in os.listdir(datapath) if os.path.isfile(os.path.join(datapath, f)) and f.endswith('.pdf')]
onlyfiles.sort()

print('Files in the folder:')
for i, w in enumerate(onlyfiles):
    print(i, '--' ,w)

Files in the folder:
0 -- RobertFrost_Poetry.pdf


In [47]:
text0 = textract.process(os.path.join(datapath, onlyfiles[0])).decode('utf-8')
print(text0[0:1000])

Classic Poetry Series

Robert Frost
- poems -

Publication Date:
2004

Publisher:

PoemHunter.Com - The World's Poetry Archive

"In White": Frost's Early Version Of Design
A dented spider like a snow drop white
On a white Heal-all, holding up a moth
Like a white piece of lifeless satin cloth Saw ever curious eye so strange a sight? Portent in little, assorted death and blight
Like the ingredients of a witches' broth? The beady spider, the flower like a froth,
And the moth carried like a paper kite.

What had that flower to do with being white,
The blue prunella every child's delight.
What brought the kindred spider to that height?
(Make we no thesis of the miller's plight.)
What but design of darkness and of night?
Design, design! Do I use the word aright?
Anonymous submission.
Robert Frost

www.PoemHunter.com - The World's Poetry Archive

2

A Boundless Moment
He halted in the wind, and -- what was that
Far in the maples, pale, but not a ghost?
He stood there bringing March against 

### Reading Text in Image Files (OCR)

In [48]:
# !sudo apt install -y tesseract-ocr

In [49]:
onlyfiles = [f for f in os.listdir(datapath) if os.path.isfile(os.path.join(datapath, f)) and f.endswith('.png')]
onlyfiles.sort()

print('Files in the folder:')
for i, w in enumerate(onlyfiles):
    print(i, '--' ,w)

Files in the folder:
0 -- 1 HgrHDlU85dKtyLonNgu2zA.png
1 -- SQLAlchemyORM.png
2 -- db_schema.png
3 -- textimage.png


In [50]:
text1 = textract.process(os.path.join(datapath, onlyfiles[3])).decode('utf-8')

print(text1[0:900])

Adobe, the Adobe logo, Acrobat, the Acrobat logo, Acrobat Capture, Adobe Garamond, Adobe
Intelligent Document Platform, Adobe PDF, Adobe Reader, Adobe Solutions Network, Aldus, Dis-
tiller, ePaper, Extreme, FrameMaker, Illustrator, InDesign, Minion, Myriad, PageMaker, Photo-
shop, Poetica, PostScript, and XMP are either registered trademarks or trademarks of Adobe
‘Systems Incorporated in the United States and/or other countries. Microsoft and Windows are
either registered trademarks or trademarks of Microsoft Corporation in the United States and/or
other countries. Apple, Mac, Macintosh, and Power Macintosh are trademarks of Apple Computer,
Inc,, registered in the United States and other countries. IBM is a registered trademark of IBM
Corporation in the United States. Sun is a trademark or registered trademark of Sun Microsys-
tems, Inc. in the United States and other countries. UNIX is


## Accessing HTML

https://docs.python.org/3/library/urllib.html  
http://www.crummy.com/software/BeautifulSoup/  
http://docs.python-requests.org/en/latest/  
http://lxml.de/  
https://docs.python.org/3/library/getpass.html  

In [51]:
import urllib
from bs4 import BeautifulSoup as bs
import requests
import lxml.html
import getpass

In [52]:
url = "https://pt.wikipedia.org/wiki/Guimar%C3%A3es_Rosa"
html_txt = urllib.request.urlopen(url).read()
soup = bs(html_txt, "html.parser")
 
[line.get('href') for line in soup.find_all('a')][0:10]    

[None,
 '#mw-head',
 '#searchInput',
 '/wiki/Ficheiro:Guimar%C3%A3es_Rosa,_anos_1960.tif',
 '/wiki/Arquivo_Nacional_(Brasil)',
 '/wiki/27_de_junho#Nascimentos',
 '/wiki/1908',
 '/wiki/Cordisburgo',
 '/wiki/Minas_Gerais',
 '/wiki/19_de_novembro']

#### Another approach: [lxml](http://lxml.de/tutorial.html) instead of beautiful soup
 

In [53]:
url = "https://pt.wikipedia.org/wiki/Guimar%C3%A3es_Rosa"
html_txt = urllib.request.urlopen(url).read()
dom =  lxml.html.fromstring(html_txt)
    
[line for line in dom.xpath('//a/@href')][0:10]   

['#mw-head',
 '#searchInput',
 '/wiki/Ficheiro:Guimar%C3%A3es_Rosa,_anos_1960.tif',
 '/wiki/Arquivo_Nacional_(Brasil)',
 '/wiki/27_de_junho#Nascimentos',
 '/wiki/1908',
 '/wiki/Cordisburgo',
 '/wiki/Minas_Gerais',
 '/wiki/19_de_novembro',
 '/wiki/1967']

#### Using [Requests](http://docs.python-requests.org/en/master/user/quickstart/), for more complex tasks  


c.f. [HTML Responses](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)

In [54]:
p = getpass.getpass()
r = requests.get('https://api.github.com/user', auth=('rsouza', p))
r.status_code

 ············


200

In [55]:
r.headers['content-type']

'application/json; charset=utf-8'

In [56]:
r.encoding

'utf-8'

In [57]:
r.text

'{"login":"rsouza","id":604914,"node_id":"MDQ6VXNlcjYwNDkxNA==","avatar_url":"https://avatars0.githubusercontent.com/u/604914?v=4","gravatar_id":"","url":"https://api.github.com/users/rsouza","html_url":"https://github.com/rsouza","followers_url":"https://api.github.com/users/rsouza/followers","following_url":"https://api.github.com/users/rsouza/following{/other_user}","gists_url":"https://api.github.com/users/rsouza/gists{/gist_id}","starred_url":"https://api.github.com/users/rsouza/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rsouza/subscriptions","organizations_url":"https://api.github.com/users/rsouza/orgs","repos_url":"https://api.github.com/users/rsouza/repos","events_url":"https://api.github.com/users/rsouza/events{/privacy}","received_events_url":"https://api.github.com/users/rsouza/received_events","type":"User","site_admin":false,"name":"Renato Rocha Souza","company":"ÖAW ACDH-CH | FGV | UFMG","blog":"https://www.oeaw.ac.at/acdh/team/current-team/

In [58]:
r.json()

{'login': 'rsouza',
 'id': 604914,
 'node_id': 'MDQ6VXNlcjYwNDkxNA==',
 'avatar_url': 'https://avatars0.githubusercontent.com/u/604914?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/rsouza',
 'html_url': 'https://github.com/rsouza',
 'followers_url': 'https://api.github.com/users/rsouza/followers',
 'following_url': 'https://api.github.com/users/rsouza/following{/other_user}',
 'gists_url': 'https://api.github.com/users/rsouza/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/rsouza/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/rsouza/subscriptions',
 'organizations_url': 'https://api.github.com/users/rsouza/orgs',
 'repos_url': 'https://api.github.com/users/rsouza/repos',
 'events_url': 'https://api.github.com/users/rsouza/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/rsouza/received_events',
 'type': 'User',
 'site_admin': False,
 'name': 'Renato Rocha Souza',
 'company': 'ÖAW ACDH-CH | FGV | UFM

## Accessing [JSON](http://json.org/)

https://docs.python.org/3/library/json.html  
https://docs.python.org/3/library/urllib.html  

In [59]:
import json

In [60]:
base_url = "http://musicbrainz.org/ws/2/"
artist_url =  urllib.parse.urljoin(base_url, 'artist/')
query_type = {"simple": {},
              "atr": {"inc": "aliases+tags+ratings"},
              "aliases": {"inc": "aliases"},
              "releases": {"inc": "releases"}}

In [61]:
def query_site(url, params, uid="", fmt="json"):
    params["fmt"] = fmt
    r = requests.get(url + uid, params=params)
    print("requesting", r.url)

    if r.status_code == requests.codes.ok:
        return r.json()
    else:
        r.raise_for_status()

In [62]:
def query_by_name(url, params, name):
    params["query"] = "artist:" + name
    return query_site(url, params)

In [63]:
def pretty_print(data, indent=4):
    if type(data) == dict:
        print(json.dumps(data, indent=indent, sort_keys=True))
    else:
        print(data)

In [64]:
results = query_by_name(artist_url, query_type["simple"], "Nirvana")
pretty_print(results['artists'])

requesting http://musicbrainz.org/ws/2/artist/?query=artist%3ANirvana&fmt=json
[{'id': '5b11f4ce-a62d-471e-81fc-a69a8278c7da', 'type': 'Group', 'type-id': 'e431f5f6-b5d2-343d-8b36-72607fffb74b', 'score': 100, 'name': 'Nirvana', 'sort-name': 'Nirvana', 'country': 'US', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'United States', 'sort-name': 'United States', 'life-span': {'ended': None}}, 'begin-area': {'id': 'a640b45c-c173-49b1-8030-973603e895b5', 'type': 'City', 'type-id': '6fd8f29a-3d0a-32fc-980d-ea697b69da78', 'name': 'Aberdeen', 'sort-name': 'Aberdeen', 'life-span': {'ended': None}}, 'disambiguation': '90s US grunge band', 'isnis': ['0000000123486830', '0000000123487390'], 'life-span': {'begin': '1988-01', 'end': '1994-04-05', 'ended': True}, 'aliases': [{'sort-name': 'ニルヴァーナ', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'ニルヴァーナ', 'locale': 'ja', 'type': 'Artist name', 'primary':

In [65]:
results.keys()

dict_keys(['created', 'count', 'offset', 'artists'])

In [66]:
print("\nARTIST:")
pretty_print(results["artists"][4])


ARTIST:
{
    "area": {
        "id": "6a264f94-6ff1-30b1-9a81-41f7bfabd616",
        "life-span": {
            "ended": null
        },
        "name": "Finland",
        "sort-name": "Finland",
        "type": "Country",
        "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de"
    },
    "country": "FI",
    "disambiguation": "Early 1980's Finnish punk band",
    "id": "85af0709-95db-4fbc-801a-120e9f4766d0",
    "life-span": {
        "ended": null
    },
    "name": "Nirvana",
    "score": 70,
    "sort-name": "Nirvana",
    "tags": [
        {
            "count": 1,
            "name": "finland"
        },
        {
            "count": 1,
            "name": "punk"
        }
    ],
    "type": "Group",
    "type-id": "e431f5f6-b5d2-343d-8b36-72607fffb74b"
}


In [67]:
artist_id = results["artists"][4]["id"]
artist_id

'85af0709-95db-4fbc-801a-120e9f4766d0'

In [68]:
artist_data = query_site(artist_url, query_type["releases"], artist_id)
releases = artist_data["releases"]
print("\nONE RELEASE:")
pretty_print(releases[0], indent=2)

requesting http://musicbrainz.org/ws/2/artist/85af0709-95db-4fbc-801a-120e9f4766d0?inc=releases&fmt=json

ONE RELEASE:
{
  "barcode": "",
  "country": "FI",
  "date": "1980",
  "disambiguation": "",
  "id": "3e25396c-5c66-4609-8e47-37f250d323c7",
  "packaging": "Cardboard/Paper Sleeve",
  "packaging-id": "f7101ce3-0384-39ce-9fde-fbbd0044d35f",
  "quality": "normal",
  "release-events": [
    {
      "area": {
        "disambiguation": "",
        "id": "6a264f94-6ff1-30b1-9a81-41f7bfabd616",
        "iso-3166-1-codes": [
          "FI"
        ],
        "name": "Finland",
        "sort-name": "Finland",
        "type": null,
        "type-id": null
      },
      "date": "1980"
    }
  ],
  "status": "Official",
  "status-id": "4e304316-386d-3409-af2e-78857eec5cfe",
  "text-representation": {
    "language": "fin",
    "script": "Latn"
  },
  "title": "Nirvana"
}


In [69]:
releases

[{'date': '1980',
  'id': '3e25396c-5c66-4609-8e47-37f250d323c7',
  'packaging-id': 'f7101ce3-0384-39ce-9fde-fbbd0044d35f',
  'barcode': '',
  'title': 'Nirvana',
  'text-representation': {'script': 'Latn', 'language': 'fin'},
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'quality': 'normal',
  'packaging': 'Cardboard/Paper Sleeve',
  'status': 'Official',
  'disambiguation': '',
  'release-events': [{'area': {'disambiguation': '',
     'type': None,
     'iso-3166-1-codes': ['FI'],
     'sort-name': 'Finland',
     'name': 'Finland',
     'id': '6a264f94-6ff1-30b1-9a81-41f7bfabd616',
     'type-id': None},
    'date': '1980'}],
  'country': 'FI'}]

In [70]:
release_titles = [r["title"] for r in releases]
print("\nALL TITLES:")
for t in release_titles:
        print(t)


ALL TITLES:
Nirvana


#### Using Pandas

http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader  

In [71]:
df_json = pd.read_json('https://api.github.com/repos/pydata/pandas/issues?per_page=5')
df_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype              
---  ------                    --------------  -----              
 0   url                       5 non-null      object             
 1   repository_url            5 non-null      object             
 2   labels_url                5 non-null      object             
 3   comments_url              5 non-null      object             
 4   events_url                5 non-null      object             
 5   html_url                  5 non-null      object             
 6   id                        5 non-null      int64              
 7   node_id                   5 non-null      object             
 8   number                    5 non-null      int64              
 9   title                     5 non-null      object             
 10  user                      5 non-null      object             
 11  labels                 

## Accessing YAML

In [72]:
import yaml

In [73]:
with open(os.path.join(datapath, 'simple.yaml'), 'r') as stream:
    try:
        yamlfile = yaml.load(stream, Loader=yaml.Loader)
        print(yamlfile)
    except yaml.YAMLError as exc:
        print(exc)

[{'martin': {'name': "Martin D'vloper", 'job': 'Developer', 'skills': ['python', 'perl', 'pascal']}}, {'tabitha': {'name': 'Tabitha Bitumen', 'job': 'Developer', 'skills': ['lisp', 'fortran', 'erlang']}}]


In [74]:
pd.DataFrame(yamlfile[0])

martin
job                  Developer
name           Martin D'vloper
skills  [python, perl, pascal]

## Accessing XML

https://docs.python.org/3/library/urllib.html

https://docs.python.org/3/library/xml.etree.elementtree.html

http://lxml.de/

http://www.w3schools.com/xml/xml_examples.asp

In [75]:
from xml.dom import minidom
#from xml.etree import ElementTree as ET
from lxml import etree as ET #Supports xpath syntax
from collections import defaultdict
from pprint import pprint

In [76]:
url = 'http://www.w3schools.com/xml/cd_catalog.xml'
xml_page = urllib.request.urlopen(url).read()
e = ET.XML(xml_page)

In [77]:
def etree_to_dict(t):
    d = {t.tag: {} if t.attrib else None}
    children = list(t)
    if children:
        dd = defaultdict(list)
        for dc in map(etree_to_dict, children):
            for k, v in dc.items():
                dd[k].append(v)
        d = {t.tag: {k:v[0] if len(v) == 1 else v for k, v in dd.items()}}
    if t.attrib:
        d[t.tag].update(('@' + k, v) for k, v in t.attrib.items())
    if t.text:
        text = t.text.strip()
        if children or t.attrib:
            if text:
              d[t.tag]['#text'] = text
        else:
            d[t.tag] = text
    return d

In [78]:
pprint(etree_to_dict(e))

{'CATALOG': {'CD': [{'ARTIST': 'Bob Dylan',
                     'COMPANY': 'Columbia',
                     'COUNTRY': 'USA',
                     'PRICE': '10.90',
                     'TITLE': 'Empire Burlesque',
                     'YEAR': '1985'},
                    {'ARTIST': 'Bonnie Tyler',
                     'COMPANY': 'CBS Records',
                     'COUNTRY': 'UK',
                     'PRICE': '9.90',
                     'TITLE': 'Hide your heart',
                     'YEAR': '1988'},
                    {'ARTIST': 'Dolly Parton',
                     'COMPANY': 'RCA',
                     'COUNTRY': 'USA',
                     'PRICE': '9.90',
                     'TITLE': 'Greatest Hits',
                     'YEAR': '1982'},
                    {'ARTIST': 'Gary Moore',
                     'COMPANY': 'Virgin records',
                     'COUNTRY': 'UK',
                     'PRICE': '10.20',
                     'TITLE': 'Still got the blues',
                

In [79]:
raw_page = urllib.request.urlopen(url)
doc = minidom.parse(raw_page)

def findTextnodes(nodeList):
    for subnode in nodeList:
        if subnode.nodeType == subnode.ELEMENT_NODE:
            print("Element node: " + subnode.tagName)
            findTextnodes(subnode.childNodes)
        elif subnode.nodeType == subnode.TEXT_NODE:
            print("text node:" + subnode.data)
            
findTextnodes(doc.childNodes)

Element node: CATALOG
text node:
  
Element node: CD
text node:
    
Element node: TITLE
text node:Empire Burlesque
text node:
    
Element node: ARTIST
text node:Bob Dylan
text node:
    
Element node: COUNTRY
text node:USA
text node:
    
Element node: COMPANY
text node:Columbia
text node:
    
Element node: PRICE
text node:10.90
text node:
    
Element node: YEAR
text node:1985
text node:
  
text node:
  
Element node: CD
text node:
    
Element node: TITLE
text node:Hide your heart
text node:
    
Element node: ARTIST
text node:Bonnie Tyler
text node:
    
Element node: COUNTRY
text node:UK
text node:
    
Element node: COMPANY
text node:CBS Records
text node:
    
Element node: PRICE
text node:9.90
text node:
    
Element node: YEAR
text node:1988
text node:
  
text node:
  
Element node: CD
text node:
    
Element node: TITLE
text node:Greatest Hits
text node:
    
Element node: ARTIST
text node:Dolly Parton
text node:
    
Element node: COUNTRY
text node:USA
text node:
    
Elem

In [80]:
root = ET.fromstring(xml_page)
cdtags = root.xpath('//CD/TITLE')
for cd in cdtags:
    print(cd.text)

Empire Burlesque
Hide your heart
Greatest Hits
Still got the blues
Eros
One night only
Sylvias Mother
Maggie May
Romanza
When a man loves a woman
Black angel
1999 Grammy Nominees
For the good times
Big Willie style
Tupelo Honey
Soulsville
The very best of
Stop
Bridge of Spies
Private Dancer
Midt om natten
Pavarotti Gala Concert
The dock of the bay
Picture book
Red
Unchain my heart


In [81]:
for cd in root.findall('CD'):
    title = cd.find('TITLE').text
    artist = cd.find('ARTIST').text
    country = cd.find('COUNTRY').text
    print('{}\t{}\t{}'.format(artist, country, title))

Bob Dylan	USA	Empire Burlesque
Bonnie Tyler	UK	Hide your heart
Dolly Parton	USA	Greatest Hits
Gary Moore	UK	Still got the blues
Eros Ramazzotti	EU	Eros
Bee Gees	UK	One night only
Dr.Hook	UK	Sylvias Mother
Rod Stewart	UK	Maggie May
Andrea Bocelli	EU	Romanza
Percy Sledge	USA	When a man loves a woman
Savage Rose	EU	Black angel
Many	USA	1999 Grammy Nominees
Kenny Rogers	UK	For the good times
Will Smith	USA	Big Willie style
Van Morrison	UK	Tupelo Honey
Jorn Hoel	Norway	Soulsville
Cat Stevens	UK	The very best of
Sam Brown	UK	Stop
T'Pau	UK	Bridge of Spies
Tina Turner	UK	Private Dancer
Kim Larsen	EU	Midt om natten
Luciano Pavarotti	UK	Pavarotti Gala Concert
Otis Redding	USA	The dock of the bay
Simply Red	EU	Picture book
The Communards	UK	Red
Joe Cocker	USA	Unchain my heart


In [82]:
cds = []
for cd in root.findall('./CD'):
        data = {}
        data["TITLE"] = cd.find('./TITLE').text
        data["ARTIST"] = cd.find('./ARTIST').text
        data["COUNTRY"] = cd.find('./COUNTRY').text
        data["PRICE"] = cd.find('./PRICE').text
        data["YEAR"] = cd.find('./YEAR').text
        cds.append(data)
cds[0:3]

[{'TITLE': 'Empire Burlesque',
  'ARTIST': 'Bob Dylan',
  'COUNTRY': 'USA',
  'PRICE': '10.90',
  'YEAR': '1985'},
 {'TITLE': 'Hide your heart',
  'ARTIST': 'Bonnie Tyler',
  'COUNTRY': 'UK',
  'PRICE': '9.90',
  'YEAR': '1988'},
 {'TITLE': 'Greatest Hits',
  'ARTIST': 'Dolly Parton',
  'COUNTRY': 'USA',
  'PRICE': '9.90',
  'YEAR': '1982'}]

## Accessing Feeds RSS

http://www.feedparser.org/  
http://docs.python.org/library/re.html  
http://www.pythonware.com/library/pil/handbook/index.htm  

In [83]:
import feedparser

In [84]:
d = feedparser.parse('https://oglobo.globo.com/rss.xml')

In [85]:
print(d['feed']['title'])
print(d['feed']['link'])
#print(d.feed.subtitle)
print(len(d['entries']))

OGlobo
https://oglobo.globo.com/
10


In [86]:
print(d['entries'][0]['title']) 
print(d.entries[0]['link'])

Comitê internacional envia dados de testes da CoronoVac para a Anvisa
https://oglobo.globo.com/sociedade/comite-internacional-envia-dados-de-testes-da-coronovac-para-anvisa-24739295


In [87]:
print(d.headers)

{'Date': 'Tue, 10 Nov 2020 22:08:29 GMT', 'Server': 'Apache', 'Referrer-Policy': 'no-referrer-when-downgrade', 'Feature-Policy': "geolocation 'none'; midi 'none'; microphone 'none'; camera 'none'; speaker 'self'; fullscreen 'self';", 'X-Frame-Options': 'SAMEORIGIN', 'Expires': '1605046118811', 'Content-Type': 'application/rss+xml;charset=UTF-8', 'Access-Control-Allow-Origin': '*', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'Content-Length': '2848', 'cache-control': 'public, max-age=602', 'Age': '55', 'grace': 'none', 'X-Cache': 'HIT', 'X-Cache-Hits': '2', 'Accept-Ranges': 'bytes', 'Strict-Transport-Security': 'max-age=15768000', 'Content-Security-Policy': "default-src 'self' 'unsafe-inline' https: data: blob:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https: blob:; img-src 'self' data: https:;", 'X-XSS-Protection': '1; mode=block', 'Connection': 'close'}


In [88]:
for post in d.entries:
    print(post.title + ": " + post.link + "\n")

Comitê internacional envia dados de testes da CoronoVac para a Anvisa: https://oglobo.globo.com/sociedade/comite-internacional-envia-dados-de-testes-da-coronovac-para-anvisa-24739295

Ministro do STF dá 48h para Anvisa prestar informações sobre vacinas contra Covid-19: https://oglobo.globo.com/sociedade/coronavirus/ministro-do-stf-da-48h-para-anvisa-prestar-informacoes-sobre-vacinas-contra-covid-19-1-24739309

Leandra Leal, Paolla Oliveira e Emanuelle Araújo pedem ajuda a bloco carnavalesco centenário: https://oglobo.globo.com/cultura/leandra-leal-paolla-oliveira-emanuelle-araujo-pedem-ajuda-bloco-carnavalesco-centenario-24739164

Justiça Eleitoral suspende propaganda de Crivella por exposição excessiva de Bolsonaro: https://oglobo.globo.com/brasil/eleicoes-2020/justica-eleitoral-suspende-propaganda-de-crivella-por-exposicao-excessiva-de-bolsonaro-1-24739182

Martha Rocha e Eduardo Paes sobem o tom e trocam acusações na Justiça Eleitoral às vésperas do primeiro turno: https://oglobo.gl

## Dealing with Big Files

Retrieving the file:

In [89]:
link = 'http://eforexcel.com/wp/wp-content/uploads/2017/07/1500000%20Sales%20Records.zip'
filename = "bigcsv.zip"

In [90]:
urllib.request.urlretrieve(link, os.path.join(datapath, filename))

('../SampleDBs/bigcsv.zip', <http.client.HTTPMessage at 0x7fb67037ab50>)

Using Pandas with chunks:

In [91]:
chunksize = 10 ** 5
num_chunks_to_read = 3

with ZipFile(os.path.join(datapath, filename), 'r') as myzip:
    print(myzip.namelist())
    unzipped = myzip.namelist()[0]
    with myzip.open(unzipped) as myfile:
        chunks = pd.read_csv((myfile), chunksize=chunksize) #, iterator=True)
        for i in range(num_chunks_to_read):
            print('Retrieving a new chunk')
            df = chunks.get_chunk()
            print(df.head(3))
            print()

['1500000 Sales Records.csv']
Retrieving a new chunk
                         Region           Country Item Type Sales Channel  \
0            Sub-Saharan Africa      South Africa    Fruits       Offline   
1  Middle East and North Africa           Morocco   Clothes        Online   
2         Australia and Oceania  Papua New Guinea      Meat       Offline   

  Order Priority Order Date   Order ID   Ship Date  Units Sold  Unit Price  \
0              M  7/27/2012  443368995   7/28/2012        1593        9.33   
1              M  9/14/2013  667593514  10/19/2013        4611      109.28   
2              M  5/15/2015  940995585    6/4/2015         360      421.89   

   Unit Cost  Total Revenue  Total Cost  Total Profit  
0       6.92       14862.69    11023.56       3839.13  
1      35.84      503890.08   165258.24     338631.84  
2     364.69      151880.40   131288.40      20592.00  

Retrieving a new chunk
                       Region      Country      Item Type Sales Channel  \
10

Unzipping the file and reading line by line:

In [92]:
with ZipFile(os.path.join(datapath, filename), 'r') as myzip:
    myzip.extractall(datapath)
    myzip.close()

In [93]:
def getstuff(filename):
    with open(filename, "r") as csvfile:
        datareader = csv.reader(csvfile)
        count = 0
        for row in datareader:
            yield(row)

In [94]:
count = 0
for row in getstuff(os.path.join(datapath, unzipped)):
    print(row)
    count +=1
    if count > 30:
        break

['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority', 'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price', 'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit']
['Sub-Saharan Africa', 'South Africa', 'Fruits', 'Offline', 'M', '7/27/2012', '443368995', '7/28/2012', '1593', '9.33', '6.92', '14862.69', '11023.56', '3839.13']
['Middle East and North Africa', 'Morocco', 'Clothes', 'Online', 'M', '9/14/2013', '667593514', '10/19/2013', '4611', '109.28', '35.84', '503890.08', '165258.24', '338631.84']
['Australia and Oceania', 'Papua New Guinea', 'Meat', 'Offline', 'M', '5/15/2015', '940995585', '6/4/2015', '360', '421.89', '364.69', '151880.40', '131288.40', '20592.00']
['Sub-Saharan Africa', 'Djibouti', 'Clothes', 'Offline', 'H', '5/17/2017', '880811536', '7/2/2017', '562', '109.28', '35.84', '61415.36', '20142.08', '41273.28']
['Europe', 'Slovakia', 'Beverages', 'Offline', 'L', '10/26/2016', '174590194', '12/4/2016', '3973', '47.45', '31.79', '188518.85'

In [95]:
#erasing files
os.remove(os.path.join(datapath, unzipped))
os.remove(os.path.join(datapath, filename))

## Using [HDF5](https://portal.hdfgroup.org/display/HDF5/HDF5)  

In [96]:
#!sudo pip install -q -U h5py  

In [97]:
import h5py

arr = np.random.randn(1000)

filename = 'random.hdf5'
#with h5py.File(os.path.join(datapath, filename), 'a') as f:   #if we'd like to append data
with h5py.File(os.path.join(datapath, filename), 'w') as f:
    dset = f.create_dataset("default", data=arr)

In [98]:
with h5py.File(os.path.join(datapath, filename), 'r') as f:
    for key in f.keys():
        print("datasets in ths hdf system:", key)
    
    data = f['default']
    print(type(data))
    print(min(data))
    print(max(data))
    print(data[:15])

datasets in ths hdf system: default
<class 'h5py._hl.dataset.Dataset'>
-2.7402203386874757
3.7513257981483683
[-1.0678731   1.88469368 -0.08366935  0.21702538  0.47980511 -0.35550758
 -1.59860092 -0.32225117 -0.26001115  0.51186456  0.5194933  -0.08569738
  0.37366525  0.1688446  -0.27633071]


In [99]:
arr1 = np.random.randn(10000)
arr2 = np.random.randn(10000)

with h5py.File(os.path.join(datapath, filename), 'w') as f:
    f.create_dataset('array_1', data=arr1)
    f.create_dataset('array_2', data=arr2)

In [100]:
with h5py.File(os.path.join(datapath, filename), 'r') as f:
    d1 = f['array_1']
    d2 = f['array_2']
    print(type(d1))
    print(type(d2))
    #data = d2[d1>0]  #error
    data = d2[d1[:]>0]
    print(data)

<class 'h5py._hl.dataset.Dataset'>
<class 'h5py._hl.dataset.Dataset'>
[ 0.07077221  0.09293002  0.121675   ...  1.87467458 -0.91006111
  1.86608903]


In [101]:
#erasing files

os.remove(os.path.join(datapath, filename))