## Introduction to Databases

### Miscellaneous Formats

In [1]:
import os
import sys
import time
import datetime
import numpy as np
import pandas as pd

In [2]:
datapath = "../SampleDBs/"

## Saving a txt file

In [3]:
with open(os.path.join(datapath, 'newfile.txt'), mode='w', encoding='utf-8') as f:
    f.write('Weight\t\t72\n')
    f.write('Height\t\t183\n')
    f.write('Age\t\t44\n')
    f.write('Gender\t\tMasculine\n')
    f.write('\n')

## Retrieving a txt file

In [4]:
with open(os.path.join(datapath, 'newfile.txt'), mode='r', encoding='utf-8') as f:
    fulltext = f.read()
    f.seek(0)
    line = f.readline()
    f.seek(0)
    list_of_lines = f.readlines()

In [5]:
print(fulltext)

Weight		72
Height		183
Age		44
Gender		Masculine




In [6]:
print(line)

Weight		72



In [7]:
print(list_of_lines)

['Weight\t\t72\n', 'Height\t\t183\n', 'Age\t\t44\n', 'Gender\t\tMasculine\n', '\n']


In [8]:
#erasing file
os.remove(os.path.join(datapath, 'newfile.txt'))

## Saving Numpy Structures

In [9]:
data = np.linspace(0,1,201)
print(data)

[0.    0.005 0.01  0.015 0.02  0.025 0.03  0.035 0.04  0.045 0.05  0.055
 0.06  0.065 0.07  0.075 0.08  0.085 0.09  0.095 0.1   0.105 0.11  0.115
 0.12  0.125 0.13  0.135 0.14  0.145 0.15  0.155 0.16  0.165 0.17  0.175
 0.18  0.185 0.19  0.195 0.2   0.205 0.21  0.215 0.22  0.225 0.23  0.235
 0.24  0.245 0.25  0.255 0.26  0.265 0.27  0.275 0.28  0.285 0.29  0.295
 0.3   0.305 0.31  0.315 0.32  0.325 0.33  0.335 0.34  0.345 0.35  0.355
 0.36  0.365 0.37  0.375 0.38  0.385 0.39  0.395 0.4   0.405 0.41  0.415
 0.42  0.425 0.43  0.435 0.44  0.445 0.45  0.455 0.46  0.465 0.47  0.475
 0.48  0.485 0.49  0.495 0.5   0.505 0.51  0.515 0.52  0.525 0.53  0.535
 0.54  0.545 0.55  0.555 0.56  0.565 0.57  0.575 0.58  0.585 0.59  0.595
 0.6   0.605 0.61  0.615 0.62  0.625 0.63  0.635 0.64  0.645 0.65  0.655
 0.66  0.665 0.67  0.675 0.68  0.685 0.69  0.695 0.7   0.705 0.71  0.715
 0.72  0.725 0.73  0.735 0.74  0.745 0.75  0.755 0.76  0.765 0.77  0.775
 0.78  0.785 0.79  0.795 0.8   0.805 0.81  0.815 0.

In [10]:
type(data)

numpy.ndarray

In [11]:
np.savetxt(os.path.join(datapath, 'data.dat'), data)

In [12]:
new_data = np.loadtxt(os.path.join(datapath, 'data.dat'))
print(new_data)

[0.    0.005 0.01  0.015 0.02  0.025 0.03  0.035 0.04  0.045 0.05  0.055
 0.06  0.065 0.07  0.075 0.08  0.085 0.09  0.095 0.1   0.105 0.11  0.115
 0.12  0.125 0.13  0.135 0.14  0.145 0.15  0.155 0.16  0.165 0.17  0.175
 0.18  0.185 0.19  0.195 0.2   0.205 0.21  0.215 0.22  0.225 0.23  0.235
 0.24  0.245 0.25  0.255 0.26  0.265 0.27  0.275 0.28  0.285 0.29  0.295
 0.3   0.305 0.31  0.315 0.32  0.325 0.33  0.335 0.34  0.345 0.35  0.355
 0.36  0.365 0.37  0.375 0.38  0.385 0.39  0.395 0.4   0.405 0.41  0.415
 0.42  0.425 0.43  0.435 0.44  0.445 0.45  0.455 0.46  0.465 0.47  0.475
 0.48  0.485 0.49  0.495 0.5   0.505 0.51  0.515 0.52  0.525 0.53  0.535
 0.54  0.545 0.55  0.555 0.56  0.565 0.57  0.575 0.58  0.585 0.59  0.595
 0.6   0.605 0.61  0.615 0.62  0.625 0.63  0.635 0.64  0.645 0.65  0.655
 0.66  0.665 0.67  0.675 0.68  0.685 0.69  0.695 0.7   0.705 0.71  0.715
 0.72  0.725 0.73  0.735 0.74  0.745 0.75  0.755 0.76  0.765 0.77  0.775
 0.78  0.785 0.79  0.795 0.8   0.805 0.81  0.815 0.

In [13]:
#erasing file
os.remove(os.path.join(datapath, 'data.dat'))

In [14]:
x = np.linspace(0, 1, 20)
y = np.random.random(20)
header = "X-Column, Y-Column\n"
header += "This is a second line"

with open(os.path.join(datapath,'data2.dat'), 'wb') as f:
#with open(os.path.join(datapath,'data2.dat'), 'w') as f:   #using text formatting and no binary files
    np.savetxt(f, [], header=header)
    for i in range(20):
        data = np.column_stack((x[i], y[i]))
        np.savetxt(f, data), print(data)
        #f.write('{:4.1f} {:.4f}\n'.format(x[i], y[i]))    #using text formatting and no binary files
        f.flush()

[[0.         0.19087582]]
[[0.05263158 0.67513309]]
[[0.10526316 0.9181597 ]]
[[0.15789474 0.50386329]]
[[0.21052632 0.00413998]]
[[0.26315789 0.73405658]]
[[0.31578947 0.53191564]]
[[0.36842105 0.14263867]]
[[0.42105263 0.4126989 ]]
[[0.47368421 0.6598822 ]]
[[0.52631579 0.02803298]]
[[0.57894737 0.06654837]]
[[0.63157895 0.71172667]]
[[0.68421053 0.61800692]]
[[0.73684211 0.30624494]]
[[0.78947368 0.64367149]]
[[0.84210526 0.33472929]]
[[0.89473684 0.2106857 ]]
[[0.94736842 0.83396408]]
[[1.         0.30411785]]


In [15]:
! cat ../SampleDBs/data2.dat

# X-Column, Y-Column
# This is a second line
0.000000000000000000e+00 1.908758206248156730e-01
5.263157894736841813e-02 6.751330943973540277e-01
1.052631578947368363e-01 9.181596973028762765e-01
1.578947368421052544e-01 5.038632936753323355e-01
2.105263157894736725e-01 4.139984396025475633e-03
2.631578947368420907e-01 7.340565775051863806e-01
3.157894736842105088e-01 5.319156420087179926e-01
3.684210526315789269e-01 1.426386737837259666e-01
4.210526315789473450e-01 4.126989046288584984e-01
4.736842105263157632e-01 6.598822014163375771e-01
5.263157894736841813e-01 2.803297691725059604e-02
5.789473684210526550e-01 6.654836761361238029e-02
6.315789473684210176e-01 7.117266739991724434e-01
6.842105263157893802e-01 6.180069205384882691e-01
7.368421052631578538e-01 3.062449414130001824e-01
7.894736842105263275e-01 6.436714908043307259e-01
8.421052631578946901e-01 3.347292875734768636e-01
8.947368421052630527e-01 2.106856992477605939e-01
9.473684210526315264e-01 8.339640796131211342e-01
1.000

In [16]:
#erasing file
os.remove(os.path.join(datapath, 'data2.dat'))

## Using Pickle

In [53]:
import pickle

data = [1, 1.2, 'a', 'b']

with open(os.path.join(datapath, 'data.pkl'), 'wb') as f:
    pickle.dump(data, f)

In [54]:
with open(os.path.join(datapath, 'data.pkl'), 'rb') as f:
    new_data = pickle.load(f)

print(new_data)

[1, 1.2, 'a', 'b']


Pickle with gzip

In [55]:
import gzip

In [56]:
data2 = [1, 1.2, 'a', 'b']

In [57]:
with gzip.open(os.path.join(datapath, 'data.pkl.gz'), 'wb') as f:
    pickle.dump(data2, f)

In [58]:
with gzip.open(os.path.join(datapath, 'data.pkl.gz'), 'rb') as f:
    new_data2 = pickle.load(f)

In [59]:
new_data2

[1, 1.2, 'a', 'b']

In [60]:
#erasing files
os.remove(os.path.join(datapath, 'data.pkl.gz'))
os.remove(os.path.join(datapath, 'data.pkl'))

## Acessing CSV Files

In [20]:
csvfile = "fakedata.csv"
datafile = os.path.join(datapath, csvfile)

#### Using pure Python:

In [21]:
data = []
with open(datafile, "r") as f:
    keys = f.readline().split('|')
    keys = [k.strip() for k in keys]
    for i in range(5):
        values = f.readline().split('|')
        values = [v.strip() for v in values]
        d = dict(zip(keys,values))
        data.append(d)
data[0:5]

[{'name': 'Fatima',
  'email': 'Quisque.varius@Integervitae.org',
  'birthdate': '11-25-01'},
 {'name': 'Katelyn',
  'email': 'mi.pede.nonummy@Sedid.ca',
  'birthdate': '11-27-03'},
 {'name': 'Gillian',
  'email': 'odio.semper@sodalesMaurisblandit.org',
  'birthdate': '02-19-14'},
 {'name': 'Preston',
  'email': 'faucibus.orci@lacusQuisque.edu',
  'birthdate': '08-07-09'},
 {'name': 'Priscilla',
  'email': 'semper.auctor@cursusvestibulum.co.uk',
  'birthdate': '08-12-01'}]

#### Using [CSV](https://docs.python.org/3/library/csv.html) module:

In [22]:
import csv

In [23]:
with open(datafile, "r") as f:
    data2 = csv.reader(f, delimiter='|')
    #data2 = csv.DictReader(f, delimiter='|')
    for row in data2:
        print(row)

['name', 'email', 'birthdate']
['Fatima', 'Quisque.varius@Integervitae.org', '11-25-01']
['Katelyn', 'mi.pede.nonummy@Sedid.ca', '11-27-03']
['Gillian', 'odio.semper@sodalesMaurisblandit.org', '02-19-14']
['Preston', 'faucibus.orci@lacusQuisque.edu', '08-07-09']
['Priscilla', 'semper.auctor@cursusvestibulum.co.uk', '08-12-01']
['Zena', 'ante@magnaPraesent.com', '11-24-11']
['Oren', 'rutrum.eu.ultrices@nec.org', '01-12-07']
['Jamalia', 'Phasellus.vitae.mauris@vel.org', '05-17-17']
['Libby', 'velit.eu@Maecenasmi.edu', '07-29-17']
['Finn', 'natoque.penatibus@lectusa.net', '06-23-10']
['Graiden', 'neque.Nullam@hendreritidante.com', '09-18-10']
['Kitra', 'quis.tristique@estmollis.com', '11-18-02']
['Baxter', 'vitae.mauris@sed.org', '04-12-17']
['Margaret', 'ullamcorper@nec.ca', '08-16-04']
['Sopoline', 'vitae.diam@velitQuisquevarius.co.uk', '09-03-06']
['Flynn', 'eget.varius@magnased.org', '08-28-14']
['Beck', 'arcu.et.pede@idblandit.co.uk', '01-14-06']
['Sheila', 'natoque.penatibus.et@matt

#### Using Pandas:

In [24]:
df_csv = pd.read_csv(datafile, sep="|")
df_csv.head()

name                                 email birthdate
0     Fatima       Quisque.varius@Integervitae.org  11-25-01
1    Katelyn              mi.pede.nonummy@Sedid.ca  11-27-03
2    Gillian  odio.semper@sodalesMaurisblandit.org  02-19-14
3    Preston        faucibus.orci@lacusQuisque.edu  08-07-09
4  Priscilla  semper.auctor@cursusvestibulum.co.uk  08-12-01

In [25]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   name       100 non-null    object
 1   email      100 non-null    object
 2   birthdate  100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB


## Manipulating [Zip Files](https://docs.python.org/3/library/zipfile.html)

In [26]:
from zipfile import ZipFile

In [27]:
compressedfile = "2013_ERCOT_Hourly_Load_Data.zip"
datafile = os.path.join(datapath, compressedfile)

In [ ]:
pd_excel = pd.read_excel(datafile, com)

In [35]:
with ZipFile(datafile, 'r') as myzip:
    print(myzip.namelist())
    unzipped = myzip.namelist()[0]
    with myzip.open(unzipped, 'r') as myfile:
        pd_excel = pd.read_excel(myfile, engine='pyxlsb')
        
pd_excel.head()

['2013_ERCOT_Hourly_Load_Data.xls']


UnsupportedOperation: seek

## [Acessing](https://pypi.python.org/pypi/xlrd) and [Writing](https://pypi.python.org/pypi/xlwt) [Excel Files](https://github.com/python-excel/tutorial/blob/master/python-excel.pdf)

In [ ]:
#!sudo pip install -U xlrd xlwt

#### Accessing a workbook

In [ ]:
import xlrd

In [ ]:
with ZipFile(datafile, 'r') as myzip:
    unzipped = myzip.namelist()[0]
    myzip.extractall(datapath)

In [ ]:
workbook = xlrd.open_workbook(os.path.join(datapath, unzipped))
sheet = workbook.sheet_by_index(0)

In [ ]:
sheet_data = [[sheet.cell_value(r, col) for col in range(sheet.ncols)] for r in range(sheet.nrows)]
sheet_data[:2]

In [ ]:
print("Number of rows in the sheet:"),
print(sheet.nrows)

In [ ]:
print("Type of data in cell (row 3, col 2):"), 
print(sheet.cell_type(3, 2))

In [ ]:
print("Value in cell (row 3, col 2):", )
print(sheet.cell_value(3, 2))

In [ ]:
print("Get a slice of values in column 3, from rows 1-3:",)
print(sheet.col_values(3, start_rowx=1, end_rowx=4))

In [ ]:
coast = sheet.col_values(1, start_rowx=1)
data3 = {}    
data3['maxvalue'] = max(coast)
data3['minvalue'] = min(coast)
data3['avgcoast'] = np.mean(coast)

rowmax = coast.index(max(coast))+1
rowmin = coast.index(min(coast))+1

data3['maxtime'] = xlrd.xldate_as_tuple(sheet.cell_value(rowmax,0), 0)
data3['mintime'] = xlrd.xldate_as_tuple(sheet.cell_value(rowmin,0), 0)

In [ ]:
data3

#### Using Pandas

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html  

In [ ]:
pd_excel = pd.read_excel(os.path.join(datapath, unzipped))
pd_excel.head()

In [ ]:
#erasing file
os.remove(os.path.join(datapath, unzipped))

#### Reading and Writing a Workbook

In [ ]:
import xlwt

In [ ]:
style0 = xlwt.easyxf('font: name Times New Roman, color-index red, bold on', num_format_str='#,##0.00')
style1 = xlwt.easyxf(num_format_str='D-MMM-YY')

In [ ]:
workbook = xlwt.Workbook()
workbook_name = 'my_workbook.xls'

worksheet1 = workbook.add_sheet('my_first_sheet')
worksheet1.write(0, 0, 'Column 1 title', style0)
worksheet1.write(0, 1, 'Column 2 title', style0)

worksheet2 = workbook.add_sheet('my_second_sheet')
worksheet2.write(0, 0, 'Itens')
worksheet2.write(0, 1, 'Price')
worksheet2.write(1, 0, 'Rice')
worksheet2.write(1, 1, 100)
worksheet2.write(2, 0, 'Beans')
worksheet2.write(2, 1, 200)
worksheet2.write(3, 0, 'Pasta')
worksheet2.write(3, 1, 500)
worksheet2.write(5, 0, 'Total')

worksheet2.write(5, 1, xlwt.Formula("B2+B3+B4"))


workbook.save(os.path.join(datapath, workbook_name))

In [ ]:
#erasing file
os.remove(os.path.join(datapath, workbook_name))

### Reading PDF Files  

More resources [here](https://textract.readthedocs.io/en/stable/) and [here](https://towardsdatascience.com/python-for-pdf-ef0fac2808b0?)

In [ ]:
#!sudo pip install -U textract

In [ ]:
import textract

In [ ]:
onlyfiles = [f for f in os.listdir(datapath) if os.path.isfile(os.path.join(datapath, f)) and f.endswith('.pdf')]
onlyfiles.sort()

print('Files in the folder:')
for i, w in enumerate(onlyfiles):
    print(i, '--' ,w)

In [ ]:
text0 = textract.process(os.path.join(datapath, onlyfiles[0])).decode('utf-8')
print(text0[0:1000])

### Reading Text in Image Files (OCR)

In [ ]:
# !sudo apt install -y tesseract-ocr

In [ ]:
onlyfiles = [f for f in os.listdir(datapath) if os.path.isfile(os.path.join(datapath, f)) and f.endswith('.png')]
onlyfiles.sort()

print('Files in the folder:')
for i, w in enumerate(onlyfiles):
    print(i, '--' ,w)

In [ ]:
text1 = textract.process(os.path.join(datapath, onlyfiles[3])).decode('utf-8')

print(text1[0:900])

## Accessing HTML

https://docs.python.org/3/library/urllib.html  
http://www.crummy.com/software/BeautifulSoup/  
http://docs.python-requests.org/en/latest/  
http://lxml.de/  
https://docs.python.org/3/library/getpass.html  

In [ ]:
import urllib
import requests

from bs4 import BeautifulSoup as bs
import lxml.html

import getpass

In [ ]:
url = "https://pt.wikipedia.org/wiki/Guimar%C3%A3es_Rosa"
html_txt = urllib.request.urlopen(url).read()
soup = bs(html_txt, "html.parser")
 
print(soup.text[0:300])

In [ ]:
[line.get('href') for line in soup.find_all('a')][0:10] 

#### Another approach: [lxml](http://lxml.de/tutorial.html) instead of beautiful soup
 

In [ ]:
url = "https://pt.wikipedia.org/wiki/Guimar%C3%A3es_Rosa"
html_txt = urllib.request.urlopen(url).read()
dom =  lxml.html.fromstring(html_txt)
    
[line for line in dom.xpath('//a/@href')][0:10]   

#### Using [Requests](http://docs.python-requests.org/en/master/user/quickstart/), for more complex tasks  


c.f. [HTML Responses](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)

In [ ]:
p = getpass.getpass()
r = requests.get('https://api.github.com/user', auth=('rsouza', p))
r.status_code

In [ ]:
r.headers['content-type']

In [ ]:
r.encoding

In [ ]:
r.text

In [ ]:
r.json()

## Accessing [JSON](http://json.org/)

https://docs.python.org/3/library/json.html  
https://docs.python.org/3/library/urllib.html  

In [ ]:
import json

In [ ]:
base_url = "http://musicbrainz.org/ws/2/"
artist_url =  urllib.parse.urljoin(base_url, 'artist/')
query_type = {"simple": {},
              "atr": {"inc": "aliases+tags+ratings"},
              "aliases": {"inc": "aliases"},
              "releases": {"inc": "releases"}}

In [ ]:
def query_site(url, params, uid="", fmt="json"):
    params["fmt"] = fmt
    r = requests.get(url + uid, params=params)
    print("requesting", r.url)

    if r.status_code == requests.codes.ok:
        return r.json()
    else:
        r.raise_for_status()

In [ ]:
def query_by_name(url, params, name):
    params["query"] = "artist:" + name
    return query_site(url, params)

In [ ]:
def pretty_print(data, indent=4):
    if type(data) == dict:
        print(json.dumps(data, indent=indent, sort_keys=True))
    else:
        print(data)

In [ ]:
results = query_by_name(artist_url, query_type["simple"], "Nirvana")
pretty_print(results['artists'])  ##format

In [ ]:
results.keys()

In [ ]:
print("\nARTIST:")
pretty_print(results["artists"][0])

In [ ]:
artist_id = results["artists"][0]["id"]
artist_id

In [ ]:
artist_data = query_site(artist_url, query_type["releases"], artist_id)
releases = artist_data["releases"]
print("\nONE RELEASE:")
pretty_print(releases[0], indent=2)

In [ ]:
releases

In [ ]:
release_titles = [r["title"] for r in releases]
print("\nALL TITLES:")
for t in release_titles:
        print(t)

#### Using Pandas

http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader  

In [ ]:
df_json = pd.read_json('https://api.github.com/repos/pydata/pandas/issues?per_page=5')
df_json.info()

In [ ]:
df_json.title.head()

## Accessing YAML

In [ ]:
import yaml

In [ ]:
with open(os.path.join(datapath, 'simple.yaml'), 'r') as stream:
    try:
        yamlfile = yaml.load(stream, Loader=yaml.Loader)
        print(yamlfile)
    except yaml.YAMLError as exc:
        print(exc)

In [ ]:
pd.DataFrame(yamlfile[0])

## Accessing XML

https://docs.python.org/3/library/urllib.html

https://docs.python.org/3/library/xml.etree.elementtree.html

http://lxml.de/

http://www.w3schools.com/xml/xml_examples.asp

In [ ]:
from xml.dom import minidom
#from xml.etree import ElementTree as ET
from lxml import etree as ET #Supports xpath syntax
from collections import defaultdict
from pprint import pprint

In [ ]:
url = 'http://www.w3schools.com/xml/cd_catalog.xml'
xml_page = urllib.request.urlopen(url).read()
e = ET.XML(xml_page)

In [ ]:
def etree_to_dict(t):
    d = {t.tag: {} if t.attrib else None}
    children = list(t)
    if children:
        dd = defaultdict(list)
        for dc in map(etree_to_dict, children):
            for k, v in dc.items():
                dd[k].append(v)
        d = {t.tag: {k:v[0] if len(v) == 1 else v for k, v in dd.items()}}
    if t.attrib:
        d[t.tag].update(('@' + k, v) for k, v in t.attrib.items())
    if t.text:
        text = t.text.strip()
        if children or t.attrib:
            if text:
              d[t.tag]['#text'] = text
        else:
            d[t.tag] = text
    return d

In [ ]:
pprint(etree_to_dict(e))

In [ ]:
raw_page = urllib.request.urlopen(url)
doc = minidom.parse(raw_page)

def findTextnodes(nodeList):
    for subnode in nodeList:
        if subnode.nodeType == subnode.ELEMENT_NODE:
            print("Element node: " + subnode.tagName)
            findTextnodes(subnode.childNodes)
        elif subnode.nodeType == subnode.TEXT_NODE:
            print("text node:" + subnode.data)
            
findTextnodes(doc.childNodes)

In [ ]:
root = ET.fromstring(xml_page)
cdtags = root.xpath('//CD/TITLE')
for cd in cdtags:
    print(cd.text)

In [ ]:
for cd in root.findall('CD'):
    title = cd.find('TITLE').text
    artist = cd.find('ARTIST').text
    country = cd.find('COUNTRY').text
    print('{}\t{}\t{}'.format(artist, country, title))

In [ ]:
cds = []
for cd in root.findall('./CD'):
        data = {}
        data["TITLE"] = cd.find('./TITLE').text
        data["ARTIST"] = cd.find('./ARTIST').text
        data["COUNTRY"] = cd.find('./COUNTRY').text
        data["PRICE"] = cd.find('./PRICE').text
        data["YEAR"] = cd.find('./YEAR').text
        cds.append(data)
cds[0:3]

## Accessing Feeds RSS

http://www.feedparser.org/  
http://docs.python.org/library/re.html  
http://www.pythonware.com/library/pil/handbook/index.htm  

In [ ]:
import feedparser

In [ ]:
d = feedparser.parse('https://oglobo.globo.com/rss.xml')

In [ ]:
print(d['feed']['title'])
print(d['feed']['link'])
#print(d.feed.subtitle)
print(len(d['entries']))

In [ ]:
print(d['entries'][0]['title']) 
print(d.entries[0]['link'])

In [ ]:
print(d.headers)

In [ ]:
for post in d.entries:
    print(post.title + ": " + post.link + "\n")

## Dealing with Big Files

Retrieving the file:

In [ ]:
link = 'http://eforexcel.com/wp/wp-content/uploads/2017/07/1500000%20Sales%20Records.zip'
filename = "bigcsv.zip"

In [ ]:
urllib.request.urlretrieve(link, os.path.join(datapath, filename))

Using Pandas with chunks:

In [ ]:
chunksize = 10 ** 5
num_chunks_to_read = 3

with ZipFile(os.path.join(datapath, filename), 'r') as myzip:
    print(myzip.namelist())
    unzipped = myzip.namelist()[0]
    with myzip.open(unzipped) as myfile:
        chunks = pd.read_csv((myfile), chunksize=chunksize) #, iterator=True)
        for i in range(num_chunks_to_read):
            print('Retrieving a new chunk')
            df = chunks.get_chunk()
            print(df.head(3))
            print()

Unzipping the file and reading line by line:

In [ ]:
with ZipFile(os.path.join(datapath, filename), 'r') as myzip:
    myzip.extractall(datapath)
    myzip.close()

In [ ]:
def getstuff(filename):
    with open(filename, "r") as csvfile:
        datareader = csv.reader(csvfile)
        count = 0
        for row in datareader:
            yield(row)

In [ ]:
count = 0
for row in getstuff(os.path.join(datapath, unzipped)):
    print(row)
    count +=1
    if count > 30:
        break

In [ ]:
#erasing files
os.remove(os.path.join(datapath, unzipped))
os.remove(os.path.join(datapath, filename))

## Using [HDF5](https://portal.hdfgroup.org/display/HDF5/HDF5)  

In [ ]:
#!sudo pip install -q -U h5py  

In [ ]:
import h5py

arr = np.random.randn(1000)

filename = 'random.hdf5'
#with h5py.File(os.path.join(datapath, filename), 'a') as f:   #if we'd like to append data
with h5py.File(os.path.join(datapath, filename), 'w') as f:
    dset = f.create_dataset("default", data=arr)

In [ ]:
with h5py.File(os.path.join(datapath, filename), 'r') as f:
    for key in f.keys():
        print("datasets in ths hdf system:", key)
    
    data = f['default']
    print(type(data))
    print(min(data))
    print(max(data))
    print(data[:15])

In [ ]:
arr1 = np.random.randn(10000)
arr2 = np.random.randn(10000)

with h5py.File(os.path.join(datapath, filename), 'w') as f:
    f.create_dataset('array_1', data=arr1)
    f.create_dataset('array_2', data=arr2)

In [ ]:
with h5py.File(os.path.join(datapath, filename), 'r') as f:
    d1 = f['array_1']
    d2 = f['array_2']
    print(type(d1))
    print(type(d2))
    #data = d2[d1>0]  #error
    data = d2[d1[:]>0]
    print(data)

In [ ]:
#erasing files

os.remove(os.path.join(datapath, filename))

### TBD

In [ ]:
#https://vaex.readthedocs.io/en/latest/

In [61]:
#https://docs.dask.org/en/latest/dataframe.html

In [ ]:
#https://www.markdownguide.org/cheat-sheet/